import { expect, test } from '@playwright/test'
import { loginAsAdmin } from './helpers/auth'

test('admin can create draft data type with pipeline component cards', async ({ page }) => {
  await loginAsAdmin(page)
  await expect(page.getByTestId('data-type-home')).toBeVisible({ timeout: 20_000 })
  await page.getByTestId('dtype-new-btn').click()
  await expect(page.getByTestId('data-type-editor')).toBeVisible({ timeout: 15_000 })
  await expect(page.getByTestId('dtype-id')).toBeEnabled({ timeout: 20_000 })
  await expect(page.getByTestId('pipeline-orchestrator')).toBeVisible()
  await expect(page.getByTestId('overview-composer')).toBeVisible()
  await expect(page.getByText('源槽位（绑定可入湖 kinds）')).toHaveCount(0)
  await expect(page.getByRole('heading', { name: '源槽位（绑定可入湖 kinds）' })).toHaveCount(0)
  await expect(page.getByTestId('pipe-add-source')).toBeVisible()
  await expect(page.getByTestId('pipe-source-card')).toHaveCount(1)
  await expect(page.getByTestId('pipe-source-row')).toHaveCount(1)
  await expect(page.getByTestId('pipe-step-label')).toBeVisible()

  const sourceCard = page.getByTestId('pipe-source-card').first()
  await sourceCard.getByTestId('pipe-card-collapse').click()
  await expect(sourceCard.getByText('允许 kinds')).toHaveCount(0)
  await sourceCard.getByTestId('pipe-card-collapse').click()
  await expect(sourceCard.getByText('允许 kinds')).toBeVisible()

  await page.getByTestId('pipe-add-source').click()
  await expect(page.getByTestId('pipe-source-card')).toHaveCount(1)
  await expect(page.getByTestId('pipe-source-row')).toHaveCount(2)
  await page.getByTestId('pipe-remove-source').nth(1).click()
  await expect(page.getByTestId('pipe-source-card')).toHaveCount(1)
  await expect(page.getByTestId('pipe-source-row')).toHaveCount(1)

  const id = `e2e_orch_${Date.now()}`
  await page.getByTestId('dtype-id').click()
  await page.getByTestId('dtype-id').pressSequentially(id, { delay: 15 })
  await page.getByTestId('dtype-title').click()
  await page.getByTestId('dtype-title').fill('E2E 管线编排类型')
  await page.getByTestId('dtype-purpose').fill('Playwright 创建的 draft 配方')
  await expect(page.getByTestId('dtype-id')).toHaveValue(id, { timeout: 10_000 })

  await page.getByTestId('palette-op-mel_spectrogram').click()
  await expect(page.getByTestId('pipe-step-mel_spectrogram')).toBeVisible()

  const melHandle = page.getByTestId('pipe-step-mel_spectrogram').getByTestId('pipe-card-drag')
  const labelBox = await page.getByTestId('pipe-step-label').boundingBox()
  expect(labelBox).toBeTruthy()
  await melHandle.hover()
  await page.mouse.down()
  await page.mouse.move(labelBox!.x + 48, labelBox!.y + 16, { steps: 12 })
  await page.mouse.up()
  const melY = (await page.getByTestId('pipe-step-mel_spectrogram').boundingBox())?.y ?? 0
  const labelY = (await page.getByTestId('pipe-step-label').boundingBox())?.y ?? 0
  expect(melY).toBeLessThan(labelY)

  await page.getByTestId('pipe-label-model').locator('.ant-select').click()
  await page.getByTitle('nvh_sem_ast').click()

  await page.getByTestId('dtype-save').click()
  await expect(page.getByText(/已保存/)).toBeVisible({ timeout: 15_000 })
  await expect(page.getByTestId('data-type-home')).toBeVisible({ timeout: 15_000 })
  await expect(page.getByTestId(`data-type-card-${id}`)).toBeVisible()
  await expect(page.getByTestId(`data-type-card-${id}`).getByText('draft', { exact: true })).toBeVisible()

  await page.getByTestId(`dtype-edit-${id}`).click()
  await expect(page.getByTestId('data-type-editor')).toBeVisible({ timeout: 15_000 })
  await expect(page.getByTestId('pipe-source-card').first()).toBeVisible()
  await expect(page.getByTestId('pipe-step-mel_spectrogram')).toBeVisible()
  await expect(page.getByTestId('pipe-step-label')).toBeVisible()
})

test('STFT cannot bind to a video-only slot', async ({ page }) => {
  await loginAsAdmin(page)
  await page.getByTestId('dtype-new-btn').click()
  await expect(page.getByTestId('pipeline-orchestrator')).toBeVisible({ timeout: 20_000 })
  await expect(page.getByTestId('dtype-id')).toBeEnabled({ timeout: 20_000 })
  await expect(page.getByTestId('pipe-source-card').first()).toBeVisible()
  await page.getByTestId('palette-op-stft_spectrogram').click()
  await expect(page.getByTestId('pipe-step-stft_spectrogram')).toBeVisible()
  const bind = page.getByTestId('pipe-bind-stft_spectrogram-in')
  await expect(bind.getByText('无兼容输入')).toBeVisible()
  await expect(page.getByTitle('槽位 primary')).toHaveCount(0)
  await expect(bind.getByTitle('数据源')).toHaveCount(0)
})

test('admin can open edit page for oms_cabin', async ({ page }) => {
  await loginAsAdmin(page)
  await page.getByTestId('dtype-edit-oms_cabin').click()
  await expect(page.getByTestId('data-type-editor')).toBeVisible({ timeout: 15_000 })
  await expect(page.getByTestId('dtype-id')).toBeDisabled()
  await expect(page.getByTestId('dtype-id')).toHaveValue('oms_cabin')
  await expect(page.getByTestId('overview-composer-list')).toBeVisible()
  await expect(page.getByTestId('overview-composer-detail')).toBeVisible()
  await expect(page.getByTestId('overview-card-cabin_multicam')).toBeVisible()
  await expect(page.getByTestId('overview-card-clip_table')).toBeVisible()
  await expect(page.getByTestId('overview-card-nvh_spl_column')).toHaveCount(0)
  await page.getByTestId('dtype-overview-preset').click()
  const presetDrop = page.locator('.ant-select-dropdown').filter({ visible: true })
  await expect(presetDrop.getByText(/audio_nvh_timeline/)).toBeVisible()
  await presetDrop.getByText(/四通道频谱时间轴/).click()
  await expect(page.getByTestId('overview-card-nvh_spl_column')).toBeVisible()
  await expect(page.getByTestId('overview-card-nvh_spectrum')).toBeVisible()
  await expect(page.getByTestId('overview-card-cabin_multicam')).toHaveCount(0)
  await expect(page.getByTestId('pipe-source-card')).toHaveCount(1)
  await expect(page.getByTestId('pipe-source-row')).toHaveCount(4)
  await expect(page.getByTestId('pipe-source-card').locator('input').first()).toHaveValue('rosbag')
  await expect(page.getByTestId('pipe-step-parse_bag')).toBeVisible()
  await expect(page.getByTestId('pipe-parse-modalities')).toBeVisible()
  await expect(
    page.getByTestId('pipe-step-parse_bag').locator('.pipe-chip').filter({ hasText: /^连续帧$/ }),
  ).toBeVisible()
  await expect(page.getByTestId('pipe-step-parse_bag').locator('.pipe-chip').filter({ hasText: /^\.mp4$/ })).toHaveCount(0)
  await expect(page.getByTestId('pipe-step-parse_bag').locator('.pipe-chip').filter({ hasText: '多模数据' })).toHaveCount(0)
  await expect(page.getByTestId('pipe-step-transcribe')).toBeVisible()
  const asrDrop = page.locator('.ant-select-dropdown').filter({ visible: true })
  await page.getByTestId('pipe-bind-transcribe-in').locator('.ant-select').click()
  await expect(asrDrop.getByTitle('ROSBAG 解析器 · .wav')).toBeVisible()
  await expect(asrDrop.getByTitle('ROSBAG 解析器 · .mp4')).toHaveCount(0)
  await page.keyboard.press('Escape')
  await expect(page.getByTestId('pipe-step-encode_preview')).toBeVisible()
  await expect(
    page.getByTestId('pipe-step-encode_preview').locator('.pipe-chip').filter({ hasText: /^\.mp4$/ }),
  ).toHaveCount(0)
  await page.getByTestId('pipe-bind-encode_preview-in').locator('.ant-select').click()
  const encodeDrop = page.locator('.ant-select-dropdown').filter({ visible: true })
  await expect(encodeDrop.getByTitle('ROSBAG 解析器 · .mp4')).toHaveCount(0)
  await expect(encodeDrop.getByTitle('ROSBAG 解析器 · 连续帧')).toBeVisible()
  await expect(encodeDrop.getByTitle('视频抽帧 · 连续帧')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByTestId('pipe-bind-transcribe-in').locator('.ant-select-multiple')).toHaveCount(0)
  const labelBind = page.getByTestId('pipe-bind-label-in')
  await expect(labelBind.locator('.ant-select-multiple')).toBeVisible()
  await expect(labelBind.getByTitle('ROSBAG 解析器 · 连续帧')).toBeVisible()
  await expect(labelBind.getByTitle('ROSBAG 解析器 · .wav')).toBeVisible()
  await expect(labelBind.getByTitle('音频 ASR · ASR 文本')).toBeVisible()
  await expect(page.getByTestId('pipe-step-label')).toBeVisible()
})
