#!/usr/bin/env python3
"""Bundle sdk_pipeline_driver + helpers into one DataWorks PyODPS3 paste file."""

from __future__ import annotations

import re
from pathlib import Path

PIPELINE_ROOT = Path(__file__).resolve().parents[1]
DATAWORKS = PIPELINE_ROOT / "dataworks"
OUT_DIR = DATAWORKS / "bundled"
FUTURE = "from __future__ import annotations"

# Order matters: dependencies first.
HELPERS: tuple[tuple[str, Path], ...] = (
    ("upload_run.py", DATAWORKS / "upload_run.py"),
    ("pipeline_dispatch.py", DATAWORKS / "pipeline_dispatch.py"),
    ("sdk_dpe_common.py", DATAWORKS / "sdk_dpe_common.py"),
    ("sdk_mc_ingest.py", DATAWORKS / "sdk_mc_ingest.py"),
    ("sdk_pipeline_driver_lib.py", DATAWORKS / "sdk_pipeline_driver_lib.py"),
)

NODE = DATAWORKS / "sdk_pipeline_driver_node.py"

IMPORT_STRIPPERS = (
    re.compile(r"^from upload_run import .+$", re.MULTILINE),
    re.compile(r"^from pipeline_dispatch import \([\s\S]*?\)\s*", re.MULTILINE),
    re.compile(r"^from pipeline_dispatch import .+$", re.MULTILINE),
    re.compile(r"^from sdk_dpe_common import \([\s\S]*?\)\s*", re.MULTILINE),
    re.compile(r"^from sdk_dpe_common import .+$", re.MULTILINE),
    re.compile(r"^from sdk_mc_ingest import .+$", re.MULTILINE),
    re.compile(r"^from sdk_pipeline_driver_lib import \([\s\S]*?\)\s*", re.MULTILINE),
    re.compile(r"^from sdk_pipeline_driver_lib import .+$", re.MULTILINE),
)


def _strip_future(source: str) -> str:
    lines = [ln for ln in source.splitlines() if ln.strip() != FUTURE]
    return "\n".join(lines).strip("\n")


def _strip_imports(source: str) -> str:
    text = source
    for pattern in IMPORT_STRIPPERS:
        text = pattern.sub("", text)
    # Collapse excess blank lines created by stripping.
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip("\n")


def bundle() -> Path:
    if not NODE.is_file():
        raise SystemExit(f"Missing node: {NODE}")

    blocks: list[str] = [
        FUTURE,
        "",
        "# sdk_pipeline_driver_node.py — paste this SINGLE file into DataWorks PyODPS3",
        "# Generated by pipeline/scripts/bundle_sdk_pipeline_driver.py",
    ]

    for name, path in HELPERS:
        if not path.is_file():
            raise SystemExit(f"Missing helper: {path}")
        body = _strip_imports(_strip_future(path.read_text(encoding="utf-8")))
        blocks.extend(
            [
                "",
                f"# === BEGIN {name} (auto-bundled) ===",
                body,
                f"# === END {name} ===",
            ]
        )

    node_body = _strip_imports(_strip_future(NODE.read_text(encoding="utf-8")))
    blocks.extend(["", "# === BEGIN sdk_pipeline_driver_node.py ===", node_body, "# === END sdk_pipeline_driver_node.py ===", ""])

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    out = OUT_DIR / "sdk_pipeline_driver_node.py"
    out.write_text("\n".join(blocks), encoding="utf-8")
    return out


def main() -> None:
    out = bundle()
    print(f"Wrote {out} ({out.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
