values:
  2d_ir: 2D 红外
  2d_rgb: 2D RGB
  3d_tof: 3D ToF
  D: D档
  M: M档
  N: N档
  P: P档
  R: R档
  adjusting_clothing: 整理衣物
  adjusting_controls: 调节控件
  adult: 成人
  afternoon: 下午
  alert: 清醒
  angry: 愤怒
  artificial: 人工光
  ask_confirm: 询问确认
  attentive: 专注
  beverage: 饮料
  book: 书籍
  both: 双向
  brow_furrow: 皱眉
  buckling_seatbelt: 系安全带
  casual_chat_with_hmi: 与 HMI 闲聊
  center_screen: 中控屏
  child: 儿童
  child_care: 照看儿童
  cigarette: 香烟
  clear_throat: 清嗓
  climate_ui: 空调界面
  cloudy: 多云
  condition_trigger: 条件触发
  cough: 咳嗽
  cry: 哭泣
  dawn: 凌晨
  deferred: 延后
  disgusted: 厌恶
  drinking: 饮水
  driver: 驾驶员
  driving: 驾驶中
  dusk: 傍晚
  dust_storm: 沙尘暴
  eating: 进食
  eating_drinking: 饮食
  eating_while_driving: 驾驶中进食
  evening: 晚上
  evening_commute: 晚高峰通勤
  execute_directly: 直接执行
  expressway: 快速路/高速
  external_event: 外部事件
  eye_wide: 睁大眼
  failed: 失败
  fearful: 恐惧
  fog: 雾
  food: 食物
  front_passenger: 副驾
  frown: 不悦
  groan: 呻吟
  guest: 访客
  happy: 高兴
  heavy_rain: 大雨
  highway: 高速公路
  hmi_command: HMI 指令
  holding_child: 抱儿童
  human_to_human: 人人对话
  humming: 哼唱
  idling: 怠速
  infant: 婴儿
  infotainment: 娱乐系统
  instrument_cluster: 仪表
  laugh: 笑
  left_mirror: 左后视镜
  left_window: 左侧窗
  light_rain: 小雨
  lip_press: 抿嘴
  local_street: 地方道路
  makeup: 化妆
  mild_fatigue: 轻度疲劳
  mixed: 混合光
  moderate_distraction: 中度分心
  moderate_fatigue: 中度疲劳
  morning: 上午
  morning_commute: 早高峰通勤
  mouth_open: mouth open
  music_player: 音乐播放器
  natural: 自然光
  nav_instruction: 导航播报
  nav_map: 导航地图
  neutral: 中性
  newspaper: 报纸
  night: 夜间
  no_hands: 双手离盘
  no_seatbelt: 未系安全带
  non_commute: 非通勤
  none: 无
  noon: 中午
  notification: 通知
  off_road: 非铺装/越野
  other: 其他
  overcast: 阴
  parked: 驻车
  parking_lot: 停车场
  partial_success: 部分成功
  passenger: 乘员
  passenger_interaction: 与乘员互动
  pet: 宠物
  petting: 抚摸宠物
  phone: 手机
  phone_call: 打电话
  phone_calling: 通话中
  phone_ui: 手机界面
  phone_use: 使用手机
  phone_using: 使用手机
  phone_while_driving: 驾驶中使用手机
  proactive_push: 主动推送
  reading: 阅读
  rear_center: 后排中
  rear_left: 后排左
  rear_mirror: 内后视镜
  rear_right: 后排右
  rear_third: 第三排
  registered: 已注册
  rejected: 已拒绝
  resting_sleeping: 休息/睡觉
  right_mirror: 右后视镜
  right_window: 右侧窗
  road_ahead: 前方道路
  rural: 乡村道路
  sad: 悲伤
  scheduled: 已计划
  seat_vibration: 座椅振动
  senior: 老年
  settings: 设置
  severe_distraction: 重度分心
  severe_fatigue: 重度疲劳
  sigh: 叹气
  silence: 沉默
  silent_execute: 静默执行
  singing: 唱歌
  slight_distraction: 轻度分心
  smile: 微笑
  smoking: 吸烟
  sneeze: 打喷嚏
  snow: 雪
  solo_talking_to_self: 独自说话
  steering_vibration: 方向盘振动
  stereo_ir: 立体红外
  success: 成功
  sunny: 晴
  surprised: 惊讶
  system_proactive: 系统主动
  teen: 青少年
  timeout: 超时
  tissue: 纸巾
  toast: 提示
  toy: 玩具
  traffic_jam: 拥堵
  unknown: 未知
  urban_arterial: 城市主干道
  urban_high: 城区高速
  urban_low: 城区低速
  user_command: 用户指令
  yawn_sound: 打哈欠
  见动作枚举: 见动作枚举
