from __future__ import annotations

# sdk_pipeline_driver_node.py — paste this SINGLE file into DataWorks PyODPS3
# Generated by pipeline/scripts/bundle_sdk_pipeline_driver.py

# === BEGIN upload_run.py (auto-bundled) ===
"""Upload run grouping: one upload session → N bags (clip_id) → one shared pipeline run_id."""

import re
from datetime import datetime, timedelta, timezone
from typing import Any

DEFAULT_UPLOADS_PREFIX = "rosbags/uploads/"
UPLOAD_RUN_MARKER_FILES = (".upload_complete", "upload_complete.json", "upload_manifest.json")
# yyyy-MM-dd-HH-mm-ss.ssss（UTC+8；ssss=4 位毫秒）
CN_TZ = timezone(timedelta(hours=8))
PIPELINE_RUN_ID_RE = re.compile(
    r"^\d{4}-\d{2}-\d{2}-\d{2}-\d{2}-\d{2}\.\d{4}$"
)

def new_pipeline_run_id(now: datetime | None = None) -> str:
    """一次 upload_run 共享的 pipeline run_id（UTC+8 毫秒时间戳，可读）。"""
    dt = now or datetime.now(CN_TZ)
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=CN_TZ)
    else:
        dt = dt.astimezone(CN_TZ)
    ms = dt.microsecond // 1000
    return f"{dt.strftime('%Y-%m-%d-%H-%M-%S')}.{ms:04d}"

def normalize_uploads_prefix(prefix: str) -> str:
    text = (prefix or DEFAULT_UPLOADS_PREFIX).strip()
    if not text.endswith("/"):
        text += "/"
    return text

def upload_run_id_from_object_key(object_key: str, uploads_prefix: str = DEFAULT_UPLOADS_PREFIX) -> str | None:
    """``rosbags/uploads/{upload_run_id}/foo.bag`` → ``upload_run_id``."""
    prefix = normalize_uploads_prefix(uploads_prefix)
    key = object_key.strip("/")
    prefix_stripped = prefix.strip("/")
    if not key.startswith(prefix_stripped):
        return None
    rest = key[len(prefix_stripped) :].lstrip("/")
    if not rest or "/" not in rest:
        return None
    upload_run_id = rest.split("/", 1)[0].strip()
    return upload_run_id or None

def solo_upload_run_id(clip_id: str) -> str:
    safe = re.sub(r"[^a-zA-Z0-9._-]+", "_", clip_id)[-48:]
    return f"solo-{safe}"

def group_bags_by_upload_run(
    bags: list[dict[str, Any]],
    *,
    uploads_prefix: str = DEFAULT_UPLOADS_PREFIX,
    allow_legacy_flat: bool = False,
) -> list[dict[str, Any]]:
    """Group flat bag rows into upload runs (legacy flat → solo upload_run per bag)."""
    prefix = normalize_uploads_prefix(uploads_prefix)
    grouped: dict[str, dict[str, Any]] = {}

    for bag in bags:
        object_key = str(bag.get("object_key") or bag.get("bag_oss_key") or "").strip()
        clip_id = str(bag.get("clip_id") or "").strip()
        if not object_key or not clip_id:
            continue
        upload_run_id = upload_run_id_from_object_key(object_key, prefix)
        if upload_run_id is None:
            if not allow_legacy_flat:
                continue
            upload_run_id = solo_upload_run_id(clip_id)
        bucket = grouped.setdefault(
            upload_run_id,
            {
                "upload_run_id": upload_run_id,
                "upload_prefix": f"{prefix.strip('/')}/{upload_run_id}/",
                "bags": [],
                "complete": True,
            },
        )
        bucket["bags"].append(dict(bag))

    runs = list(grouped.values())
    runs.sort(key=lambda item: str(item.get("upload_run_id") or ""))
    return runs

def mark_upload_run_complete_flags(
    upload_runs: list[dict[str, Any]],
    *,
    mount_root: Any,
    uploads_prefix: str = DEFAULT_UPLOADS_PREFIX,
) -> list[dict[str, Any]]:
    """Set ``complete`` from marker files under each upload directory (DPE mount path)."""
    prefix = normalize_uploads_prefix(uploads_prefix)
    out: list[dict[str, Any]] = []
    for run in upload_runs:
        item = dict(run)
        upload_run_id = str(item.get("upload_run_id") or "").strip()
        if not upload_run_id:
            continue
        if str(upload_run_id).startswith("solo-"):
            item["complete"] = True
            out.append(item)
            continue
        upload_dir = mount_root / prefix.strip("/") / upload_run_id
        item["complete"] = any((upload_dir / name).is_file() for name in UPLOAD_RUN_MARKER_FILES)
        out.append(item)
    return out

def upload_run_state_oss_key(upload_run_id: str) -> str:
    return f"pipeline/upload_runs/{upload_run_id}.json"
# === END upload_run.py ===

# === BEGIN pipeline_dispatch.py (auto-bundled) ===
"""Pipeline dispatch: pick clip/run for scheduled DataWorks workflow.

**Primary (all DW editions):** ``job0_dispatch`` writes ``pipeline/dispatch/latest.json``
on OSS; downstream PyODPS nodes call ``resolve_pipeline_context()`` to read it.
No assignment node or node-context output params required.

Optional: hand-set ``clip_id``/``run_id`` in a node's parameter panel for single-clip debug.
Optional (DataWorks Standard+): assignment node + ``dispatch_json`` in args.
"""

import json
import os
import re
import uuid
from datetime import datetime, timezone
from typing import Any, Callable

try:
    import oss2
except ImportError:  # pragma: no cover - DataWorks driver often lacks oss2
    oss2 = None  # type: ignore[assignment]

try:
    import alibabacloud_oss_v2 as oss_v2
except ImportError:  # pragma: no cover
    oss_v2 = None  # type: ignore[assignment]

REQUIRED_PIPELINE_STEPS: tuple[str, ...] = (
    "job1_parse",
    "job1_align",
    "job2_labeling",
    "job2_embedding",
    "job3_labeling_by_other_model",
    "job4_label_merge_and_compare",
)

LEGACY_PIPELINE_STEPS: tuple[str, ...] = (
    "job1_parse",
    "job2_sample",
    "job2_asr",
    "job3_label",
    "job4_embed",
)

DEFAULT_DISPATCH_OSS_KEY = "pipeline/dispatch/latest.json"
DEFAULT_DISCOVER_OSS_KEY = "pipeline/discover/latest.json"
DEFAULT_UPLOADS_PREFIX = "rosbags/uploads/"
TAXONOMY_LATEST_OSS_KEY = "config/taxonomy/latest.json"

DISPATCH_OUTPUT_KEYS: tuple[str, ...] = (
    "action",
    "reason",
    "clip_id",
    "run_id",
    "clip_dir_name",
    "bag_oss_key",
)

_UNRESOLVED_DW_PLACEHOLDER = re.compile(r"^\$\{[^}]+\}$")

def is_unresolved_dw_placeholder(value: str | None) -> bool:
    if value is None:
        return False
    return bool(_UNRESOLVED_DW_PLACEHOLDER.match(str(value).strip()))

def read_skynet_task_input() -> dict[str, str]:
    """Read DataWorks node-context inputs from SKYNET_TASK_INPUT."""
    raw = (os.environ.get("SKYNET_TASK_INPUT") or "").strip()
    if not raw or raw == "{}":
        return {}
    try:
        loaded = json.loads(raw)
    except json.JSONDecodeError:
        return {}
    if not isinstance(loaded, dict):
        return {}
    resolved: dict[str, str] = {}
    for key, value in loaded.items():
        if value is None:
            continue
        text = str(value).strip()
        if not text or is_unresolved_dw_placeholder(text):
            continue
        resolved[str(key)] = text
    return resolved

def read_pyodps_args() -> dict[str, str]:
    """Read resolved scheduling / node-context values injected into global ``args``."""
    try:
        node_args = args  # type: ignore[name-defined]
    except NameError:
        return {}
    if not isinstance(node_args, dict):
        return {}
    resolved: dict[str, str] = {}
    for key, value in node_args.items():
        if value is None:
            continue
        text = str(value).strip()
        if not text or is_unresolved_dw_placeholder(text):
            continue
        resolved[str(key)] = text
    return resolved

def resolve_node_param(
    name: str,
    get_arg: Callable[[str, str | None], str | None],
    default: str | None = None,
) -> str | None:
    """Resolve one param from args, SKYNET_TASK_INPUT, then get_arg (skip unresolved ${...})."""
    for candidate in (
        read_pyodps_args().get(name),
        read_skynet_task_input().get(name),
        get_arg(name, default),
    ):
        if candidate is None:
            continue
        text = str(candidate).strip()
        if not text or is_unresolved_dw_placeholder(text):
            continue
        return text
    return default if default is not None else None

def _sql_string_literal(value: str) -> str:
    return "'" + str(value).replace("'", "''") + "'"

def utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()

def _is_valid_ds(value: str) -> bool:
    return len(value) == 8 and value.isdigit()

def resolve_dispatch_ds(
    get_arg: Callable[[str, str | None], str | None] | None = None,
) -> str | None:
    ds = ""
    if get_arg is not None:
        ds = (resolve_node_param("ds", get_arg, "") or "").strip()
    if not ds or is_unresolved_dw_placeholder(ds) or ds.lower() == "bizdate":
        ds = (os.environ.get("SKYNET_BIZDATE") or "").strip()
    return ds if ds and _is_valid_ds(ds) else None

def _partition_ds_value(part_name: str) -> str:
    part_name = part_name.strip()
    if part_name.startswith("ds="):
        return part_name.split("=", 1)[1].strip().strip("'").strip('"')
    return part_name

def _list_ds_partitions_client(client: Any, table_name: str) -> list[str]:
    if not client.exist_table(table_name):
        return []
    table = client.get_table(table_name)
    if not table.table_schema.partitions:
        return []
    values = {_partition_ds_value(str(part.name)) for part in table.partitions}
    return sorted((v for v in values if _is_valid_ds(v)), reverse=True)

def _pipeline_step_ds_predicate(
    client: Any,
    table_name: str,
    get_arg: Callable[[str, str | None], str | None] | None,
) -> str:
    parts = _list_ds_partitions_client(client, table_name)
    if parts:
        recent = parts[:32]
        if len(recent) == 1:
            return f"ds = {_sql_string_literal(recent[0])}"
        in_list = ", ".join(_sql_string_literal(p) for p in recent)
        return f"ds IN ({in_list})"
    ds = resolve_dispatch_ds(get_arg)
    if not ds:
        raise ValueError(
            "pipeline_step query requires ds partition; set workflow ds=${bizdate} "
            "or rely on SKYNET_BIZDATE"
        )
    return f"ds = {_sql_string_literal(ds)}"

def is_pipeline_run_complete(
    client: Any,
    table_prefix: str,
    run_id: str,
    *,
    required_steps: tuple[str, ...] = REQUIRED_PIPELINE_STEPS,
    get_arg: Callable[[str, str | None], str | None] | None = None,
) -> bool:
    if not run_id:
        return False
    table_name = f"{table_prefix}pipeline_step"
    ds_pred = _pipeline_step_ds_predicate(client, table_name, get_arg)
    sql = (
        f"SELECT step_id, MAX(CASE WHEN status = 'completed' THEN 1 ELSE 0 END) AS ok "
        f"FROM {table_name} WHERE run_id = {_sql_string_literal(run_id)} "
        f"AND {ds_pred} "
        f"GROUP BY step_id"
    )
    completed: set[str] = set()
    with client.execute_sql(sql).open_reader() as reader:
        for row in reader:
            step_id = str(row[0])
            if int(row[1]) == 1:
                completed.add(step_id)
    return all(step in completed for step in required_steps)

def list_dim_clips(client: Any, table_prefix: str) -> list[dict[str, Any]]:
    table_name = f"{table_prefix}dim_clip"
    sql = (
        f"SELECT clip_id, clip_dir_name, content_hash, bag_oss_key, active_run_id, created_at "
        f"FROM {table_name} ORDER BY created_at ASC"
    )
    rows: list[dict[str, Any]] = []
    with client.execute_sql(sql).open_reader() as reader:
        for record in reader:
            rows.append(
                {
                    "clip_id": str(record[0]),
                    "clip_dir_name": str(record[1] or ""),
                    "content_hash": str(record[2] or ""),
                    "bag_oss_key": str(record[3] or ""),
                    "active_run_id": str(record[4] or "") or None,
                    "created_at": str(record[5] or ""),
                }
            )
    return rows

def pick_dispatch_target(
    client: Any,
    table_prefix: str,
    *,
    required_steps: tuple[str, ...] = REQUIRED_PIPELINE_STEPS,
    get_arg: Callable[[str, str | None], str | None] | None = None,
) -> dict[str, Any]:
    """Return dispatch payload with action=run|idle."""
    pipeline_version = "clip_omni_v2"
    if get_arg is not None:
        pipeline_version = str(get_arg("pipeline_version", pipeline_version) or pipeline_version)
    for clip in list_dim_clips(client, table_prefix):
        clip_id = clip["clip_id"]
        active_run_id = clip.get("active_run_id")
        if active_run_id and is_pipeline_run_complete(
            client,
            table_prefix,
            active_run_id,
            required_steps=required_steps,
            get_arg=get_arg,
        ):
            continue
        if active_run_id:
            run_id = active_run_id
            reason = "resume_incomplete"
        else:
            run_id = str(uuid.uuid4())
            reason = "new_run"
        return {
            "action": "run",
            "reason": reason,
            "clip_id": clip_id,
            "run_id": run_id,
            "clip_dir_name": clip.get("clip_dir_name") or "",
            "bag_oss_key": clip.get("bag_oss_key") or "",
            "content_hash": clip.get("content_hash") or "",
            "active_run_id_before": active_run_id,
            "pipeline_version": pipeline_version,
            "dispatched_at": utc_now_iso(),
        }
    return {
        "action": "idle",
        "reason": "no_pending_clip",
        "clip_id": "",
        "run_id": "",
        "clip_dir_name": "",
        "bag_oss_key": "",
        "pipeline_version": pipeline_version,
        "dispatched_at": utc_now_iso(),
    }

def _dispatch_item_from_clip(
    clip: dict[str, Any],
    *,
    run_id: str,
    reason: str,
    prefix_template: str,
    runs_subdir_template: str,
) -> dict[str, str]:
    clip_id = str(clip.get("clip_id") or "").strip()
    run_id = str(run_id or "").strip()
    if not clip_id or not run_id:
        raise ValueError(f"invalid dispatch item: clip_id={clip_id!r} run_id={run_id!r}")
    bag_oss_key = str(
        clip.get("bag_oss_key") or clip.get("object_key") or ""
    ).strip()
    clip_prefix = prefix_template.format(clip_id=clip_id).strip("/")
    runs_subdir = runs_subdir_template.format(run_id=run_id).strip("/")
    run_relpath = f"{clip_prefix}/{runs_subdir}"
    return {
        "clip_id": clip_id,
        "run_id": run_id,
        "clip_dir_name": str(clip.get("clip_dir_name") or "").strip(),
        "bag_oss_key": bag_oss_key,
        "content_hash": str(clip.get("content_hash") or "").strip(),
        "run_relpath": run_relpath,
        "reason": reason,
    }

def _upload_run_state_key(upload_run_id: str) -> str:
    return f"pipeline/upload_runs/{upload_run_id}.json"

def read_upload_run_state_from_oss(
    *,
    upload_run_id: str,
    bucket_name: str,
    endpoint: str,
    account: Any,
    region: str | None = None,
    get_arg: Callable[[str, str | None], str | None] | None = None,
) -> dict[str, Any] | None:
    return read_dispatch_from_oss(
        bucket_name=bucket_name,
        object_key=_upload_run_state_key(upload_run_id),
        endpoint=endpoint,
        account=account,
        region=region,
        get_arg=get_arg,
    )

def write_upload_run_state_to_oss(
    *,
    payload: dict[str, Any],
    bucket_name: str,
    endpoint: str,
    account: Any,
    region: str | None = None,
    get_arg: Callable[[str, str | None], str | None] | None = None,
) -> None:
    upload_run_id = str(payload.get("upload_run_id") or "").strip()
    if not upload_run_id:
        raise ValueError("upload_run state missing upload_run_id")
    write_dispatch_to_oss(
        bucket_name=bucket_name,
        object_key=_upload_run_state_key(upload_run_id),
        endpoint=endpoint,
        account=account,
        payload=payload,
        region=region,
        get_arg=get_arg,
    )

def pick_dispatch_upload_run(
    client: Any,
    table_prefix: str,
    *,
    required_steps: tuple[str, ...] = REQUIRED_PIPELINE_STEPS,
    get_arg: Callable[[str, str | None], str | None] | None = None,
    discover_payload: dict[str, Any] | None = None,
    oss_account: Any | None = None,
    oss_bucket: str | None = None,
    oss_endpoint: str | None = None,
    prefix_template: str = "clips/{clip_id}/",
    runs_subdir_template: str = "runs/{run_id}/",
) -> dict[str, Any]:
    """Pick exactly ONE upload_run (one user upload); all clips share one pipeline run_id."""
    pipeline_version = "sdk_v1"
    if get_arg is not None:
        pipeline_version = str(get_arg("pipeline_version", pipeline_version) or pipeline_version)

    upload_runs = (discover_payload or {}).get("upload_runs") or []
    candidates: list[dict[str, Any]] = []
    for raw in upload_runs:
        if not isinstance(raw, dict):
            continue
        if not raw.get("complete", True):
            continue
        bags = raw.get("bags") or raw.get("items") or []
        new_count = int(raw.get("new_count") or len(bags) or 0)
        if new_count <= 0 or not bags:
            continue
        upload_run_id = str(raw.get("upload_run_id") or "").strip()
        if not upload_run_id:
            continue
        status = ""
        if oss_account and oss_bucket and oss_endpoint:
            state = read_upload_run_state_from_oss(
                upload_run_id=upload_run_id,
                bucket_name=oss_bucket,
                endpoint=oss_endpoint,
                account=oss_account,
                region=(get_arg("cloud_region", "cn_shanghai") if get_arg else "cn_shanghai"),
                get_arg=get_arg,
            )
            if state:
                status = str(state.get("status") or "").strip().lower()
        if status in {"dispatched", "processing", "completed"}:
            continue
        candidates.append(raw)

    candidates.sort(key=lambda item: str(item.get("upload_run_id") or ""))
    if not candidates:
        return {
            "action": "idle",
            "reason": "no_pending_upload_run",
            "mode": "upload_run",
            "upload_run_id": "",
            "pipeline_run_id": "",
            "items": [],
            "clip_id": "",
            "run_id": "",
            "pipeline_version": pipeline_version,
            "dispatched_at": utc_now_iso(),
        }

    chosen = candidates[0]
    upload_run_id = str(chosen["upload_run_id"])
    pipeline_run_id = new_pipeline_run_id()
    items: list[dict[str, str]] = []
    for bag in chosen.get("bags") or []:
        if not isinstance(bag, dict):
            continue
        clip_id = str(bag.get("clip_id") or "").strip()
        if not clip_id:
            continue
        items.append(
            _dispatch_item_from_clip(
                {
                    "clip_id": clip_id,
                    "clip_dir_name": str(bag.get("clip_dir_name") or ""),
                    "content_hash": str(bag.get("content_hash") or ""),
                    "bag_oss_key": str(bag.get("object_key") or bag.get("bag_oss_key") or ""),
                },
                run_id=pipeline_run_id,
                reason="upload_run",
                prefix_template=prefix_template,
                runs_subdir_template=runs_subdir_template,
            )
        )
        items[-1]["upload_run_id"] = upload_run_id

    if not items:
        return {
            "action": "idle",
            "reason": "upload_run_empty",
            "mode": "upload_run",
            "upload_run_id": upload_run_id,
            "pipeline_run_id": "",
            "items": [],
            "clip_id": "",
            "run_id": "",
            "pipeline_version": pipeline_version,
            "dispatched_at": utc_now_iso(),
        }

    first = items[0]
    return {
        "action": "run",
        "reason": "upload_run",
        "mode": "upload_run",
        "upload_run_id": upload_run_id,
        "pipeline_run_id": pipeline_run_id,
        "batch_size": len(items),
        "batch_source": "upload_run",
        "items": items,
        "clip_id": first["clip_id"],
        "run_id": pipeline_run_id,
        "clip_dir_name": first.get("clip_dir_name") or "",
        "bag_oss_key": first.get("bag_oss_key") or "",
        "pipeline_version": pipeline_version,
        "dispatched_at": utc_now_iso(),
        "upload_run_state": {
            "upload_run_id": upload_run_id,
            "pipeline_run_id": pipeline_run_id,
            "status": "dispatched",
            "clip_count": len(items),
            "clips": items,
            "dispatched_at": utc_now_iso(),
        },
    }

def pick_dispatch_batch(
    client: Any,
    table_prefix: str,
    *,
    required_steps: tuple[str, ...] = REQUIRED_PIPELINE_STEPS,
    get_arg: Callable[[str, str | None], str | None] | None = None,
    discover_payload: dict[str, Any] | None = None,
    max_batch: int = 32,
    prefix_template: str = "clips/{clip_id}/",
    runs_subdir_template: str = "runs/{run_id}/",
) -> dict[str, Any]:
    """Pick up to ``max_batch`` clips; write ``items[]`` for multi-row DPE downstream."""
    pipeline_version = "clip_omni_v2"
    batch_source = "discover_new" if discover_payload else "dim_pending"
    if get_arg is not None:
        pipeline_version = str(get_arg("pipeline_version", pipeline_version) or pipeline_version)
        batch_source = str(get_arg("batch_source", batch_source) or batch_source).strip().lower()

    if batch_source in {"upload_run", "upload"}:
        return pick_dispatch_upload_run(
            client,
            table_prefix,
            required_steps=required_steps,
            get_arg=get_arg,
            discover_payload=discover_payload,
            prefix_template=prefix_template,
            runs_subdir_template=runs_subdir_template,
        )

    limit = max(1, min(int(max_batch or 32), 128))
    source_clips: list[dict[str, Any]] = []

    if batch_source in {"discover_new", "discover_all", "discover"} and discover_payload:
        raw_items = discover_payload.get("items") or []
        if batch_source == "discover_all":
            raw_items = discover_payload.get("pending") or raw_items
        for raw in raw_items:
            if not isinstance(raw, dict):
                continue
            source_clips.append(
                {
                    "clip_id": str(raw.get("clip_id") or ""),
                    "clip_dir_name": str(raw.get("clip_dir_name") or ""),
                    "content_hash": str(raw.get("content_hash") or ""),
                    "bag_oss_key": str(raw.get("object_key") or raw.get("bag_oss_key") or ""),
                }
            )
            if len(source_clips) >= limit:
                break

    if not source_clips:
        batch_source = "dim_pending"
        for clip in list_dim_clips(client, table_prefix):
            clip_id = str(clip.get("clip_id") or "").strip()
            if not clip_id:
                continue
            active_run_id = clip.get("active_run_id")
            if active_run_id and is_pipeline_run_complete(
                client,
                table_prefix,
                str(active_run_id),
                required_steps=required_steps,
                get_arg=get_arg,
            ):
                continue
            source_clips.append(clip)
            if len(source_clips) >= limit:
                break

    items: list[dict[str, str]] = []
    for clip in source_clips:
        clip_id = str(clip.get("clip_id") or "").strip()
        if not clip_id:
            continue
        active_run_id = clip.get("active_run_id")
        if active_run_id and batch_source == "dim_pending":
            run_id = str(active_run_id)
            reason = "resume_incomplete"
        else:
            run_id = str(uuid.uuid4())
            reason = "new_run"
        items.append(
            _dispatch_item_from_clip(
                clip,
                run_id=run_id,
                reason=reason,
                prefix_template=prefix_template,
                runs_subdir_template=runs_subdir_template,
            )
        )

    if not items:
        return {
            "action": "idle",
            "reason": "no_pending_clip",
            "mode": "batch",
            "batch_id": "",
            "items": [],
            "clip_id": "",
            "run_id": "",
            "pipeline_version": pipeline_version,
            "dispatched_at": utc_now_iso(),
        }

    first = items[0]
    return {
        "action": "run",
        "reason": f"batch_{batch_source}",
        "mode": "batch",
        "batch_id": str(uuid.uuid4()),
        "batch_size": len(items),
        "batch_source": batch_source,
        "items": items,
        "clip_id": first["clip_id"],
        "run_id": first["run_id"],
        "clip_dir_name": first.get("clip_dir_name") or "",
        "bag_oss_key": first.get("bag_oss_key") or "",
        "pipeline_version": pipeline_version,
        "dispatched_at": utc_now_iso(),
    }

def write_discover_manifest_to_oss(
    *,
    bucket_name: str,
    object_key: str,
    endpoint: str,
    account: Any,
    payload: dict[str, Any],
    region: str | None = None,
    get_arg: Callable[[str, str | None], str | None] | None = None,
) -> None:
    write_dispatch_to_oss(
        bucket_name=bucket_name,
        object_key=object_key,
        endpoint=endpoint,
        account=account,
        payload=payload,
        region=region,
        get_arg=get_arg,
    )

def read_discover_manifest_from_oss(
    *,
    bucket_name: str,
    object_key: str,
    endpoint: str,
    account: Any,
    region: str | None = None,
    get_arg: Callable[[str, str | None], str | None] | None = None,
) -> dict[str, Any] | None:
    raw = read_dispatch_from_oss(
        bucket_name=bucket_name,
        object_key=object_key,
        endpoint=endpoint,
        account=account,
        region=region,
        get_arg=get_arg,
    )
    return raw

def _normalize_batch_items(payload: dict[str, Any]) -> list[dict[str, Any]]:
    items = payload.get("items")
    if isinstance(items, list) and items:
        normalized: list[dict[str, Any]] = []
        for raw in items:
            if not isinstance(raw, dict):
                continue
            clip_id = str(raw.get("clip_id") or "").strip()
            run_id = str(raw.get("run_id") or "").strip()
            if not clip_id or not run_id:
                continue
            normalized.append(dict(raw))
        if normalized:
            return normalized
    clip_id = str(payload.get("clip_id") or "").strip()
    run_id = str(payload.get("run_id") or "").strip()
    if clip_id and run_id:
        return [
            {
                "clip_id": clip_id,
                "run_id": run_id,
                "clip_dir_name": str(payload.get("clip_dir_name") or ""),
                "bag_oss_key": str(payload.get("bag_oss_key") or ""),
                "run_relpath": str(payload.get("run_relpath") or ""),
            }
        ]
    return []

def resolve_pipeline_batch_context(
    get_arg: Callable[[str, str | None], str | None],
    *,
    odps_client: Any | None = None,
    oss_account: Any | None = None,
    oss_endpoint: str | None = None,
    oss_bucket: str | None = None,
) -> dict[str, Any]:
    """Like resolve_pipeline_context but exposes ``items[]`` for multi-row DPE."""
    ctx = resolve_pipeline_context(
        get_arg,
        odps_client=odps_client,
        oss_account=oss_account,
        oss_endpoint=oss_endpoint,
        oss_bucket=oss_bucket,
    )
    if not ctx.get("should_run"):
        return {**ctx, "items": [], "batch_size": 0, "mode": "single"}

    payload: dict[str, Any] | None = None
    dispatch_key = (
        resolve_node_param("dispatch_oss_key", get_arg, DEFAULT_DISPATCH_OSS_KEY)
        or DEFAULT_DISPATCH_OSS_KEY
    ).strip()
    bucket = (oss_bucket or resolve_node_param("oss_bucket", get_arg, "") or "").strip()
    if oss_account and bucket:
        region = resolve_node_param("cloud_region", get_arg, "cn_shanghai") or "cn_shanghai"
        endpoint = (oss_endpoint or resolve_node_param("oss_endpoint", get_arg, "") or "").strip()
        if not endpoint:
            endpoint = resolve_oss_http_endpoint(region, get_arg=get_arg)
        payload = read_dispatch_from_oss(
            bucket_name=bucket,
            object_key=dispatch_key,
            endpoint=endpoint,
            account=oss_account,
            region=region,
            get_arg=get_arg,
        )

    prefix_template = resolve_node_param("oss_prefix_template", get_arg, "clips/{clip_id}/") or "clips/{clip_id}/"
    runs_subdir_template = (
        resolve_node_param("oss_runs_subdir", get_arg, "runs/{run_id}/") or "runs/{run_id}/"
    )

    items = _normalize_batch_items(payload or ctx)
    enriched: list[dict[str, Any]] = []
    upload_run_id = str((payload or {}).get("upload_run_id") or ctx.get("upload_run_id") or "")
    pipeline_run_id = str((payload or {}).get("pipeline_run_id") or ctx.get("run_id") or "")
    for raw in items:
        item = dict(raw)
        if upload_run_id:
            item["upload_run_id"] = upload_run_id
        if pipeline_run_id and not str(item.get("run_id") or "").strip():
            item["run_id"] = pipeline_run_id
        if not str(item.get("run_relpath") or "").strip():
            item = _dispatch_item_from_clip(
                item,
                run_id=str(item.get("run_id") or ""),
                reason=str(item.get("reason") or "batch"),
                prefix_template=prefix_template,
                runs_subdir_template=runs_subdir_template,
            )
        if not str(item.get("bag_oss_key") or "").strip():
            item["bag_oss_key"] = str(ctx.get("bag_oss_key") or "")
        enriched.append(item)

    mode = "batch" if len(enriched) > 1 else "single"
    if str((payload or {}).get("mode") or "") == "upload_run":
        mode = "upload_run"
    first = enriched[0]
    return {
        **ctx,
        "mode": mode,
        "batch_size": len(enriched),
        "items": enriched,
        "upload_run_id": upload_run_id,
        "pipeline_run_id": pipeline_run_id or str(first.get("run_id") or ctx.get("run_id") or ""),
        "clip_id": str(first.get("clip_id") or ctx.get("clip_id") or ""),
        "run_id": str(first.get("run_id") or ctx.get("run_id") or ""),
        "bag_oss_key": str(first.get("bag_oss_key") or ctx.get("bag_oss_key") or ""),
    }

def _normalize_oss_region(region: str) -> str:
    return region.replace("_", "-")

def default_oss_http_endpoint(region: str, *, use_internal: bool = True) -> str:
    """Regional OSS HTTP endpoint; DataWorks/MaxCompute should use internal by default."""
    region_id = _normalize_oss_region(region)
    internal_suffix = "-internal" if use_internal else ""
    return f"https://oss-{region_id}{internal_suffix}.aliyuncs.com"

def resolve_oss_http_endpoint(
    region: str,
    get_arg: Callable[[str, str | None], str | None] | None = None,
    *,
    explicit_endpoint: str | None = None,
) -> str:
    endpoint = (explicit_endpoint or "").strip()
    if not endpoint and get_arg is not None:
        endpoint = (resolve_node_param("oss_endpoint", get_arg, "") or "").strip()
    if endpoint:
        return endpoint
    use_internal = True
    if get_arg is not None:
        raw = resolve_node_param("oss_use_internal", get_arg, "true") or "true"
        use_internal = str(raw).lower() not in {"0", "false", "no"}
    return default_oss_http_endpoint(region, use_internal=use_internal)

def _oss_credentials(account: Any) -> tuple[str, str]:
    access_id = getattr(account, "access_id", None) or getattr(account, "access_key_id", None)
    secret = getattr(account, "secret_access_key", None) or getattr(account, "access_key_secret", None)
    if not access_id or not secret:
        raise RuntimeError("OSS credentials missing on ODPS account")
    return str(access_id), str(secret)

def _account_security_token(account: Any) -> str:
    for attr in ("sts_token", "security_token", "token"):
        value = getattr(account, attr, None)
        if value:
            return str(value)
    return ""

def resolve_dispatch_oss_credentials(
    account: Any,
    get_arg: Callable[[str, str | None], str | None] | None = None,
) -> tuple[str, str, str]:
    """Return (access_key_id, access_key_secret, security_token). Token may be empty."""
    if get_arg is not None:
        ak = (
            resolve_node_param("oss_vl_access_key_id", get_arg, "")
            or resolve_node_param("oss_access_key_id", get_arg, "")
            or ""
        ).strip()
        sk = (
            resolve_node_param("oss_vl_access_key_secret", get_arg, "")
            or resolve_node_param("oss_access_key_secret", get_arg, "")
            or ""
        ).strip()
        if ak and sk and not ak.startswith("STS."):
            return ak, sk, ""
    access_id, secret = _oss_credentials(account)
    token = _account_security_token(account)
    if access_id.startswith("STS.") and not token:
        raise RuntimeError(
            "OSS STS credentials from o.account require security_token; "
            "set oss_vl_access_key_id + oss_vl_access_key_secret in workflow params"
        )
    return access_id, secret, token

def _make_oss_v2_client(
    access_key_id: str,
    access_key_secret: str,
    *,
    region: str,
    endpoint: str | None = None,
    security_token: str | None = None,
) -> Any:
    if oss_v2 is None:
        raise RuntimeError("alibabacloud_oss_v2 is required for OSS dispatch I/O")
    cfg = oss_v2.config.load_default()
    if security_token:
        cfg.credentials_provider = oss_v2.credentials.StaticCredentialsProvider(
            access_key_id,
            access_key_secret,
            security_token,
        )
    else:
        cfg.credentials_provider = oss_v2.credentials.StaticCredentialsProvider(
            access_key_id,
            access_key_secret,
        )
    cfg.region = _normalize_oss_region(region)
    if endpoint:
        cfg.endpoint = endpoint
    return oss_v2.Client(cfg)

def _is_oss_object_missing(exc: BaseException) -> bool:
    status = getattr(exc, "status_code", None)
    if status == 404:
        return True
    code = str(getattr(exc, "code", "") or "")
    if code in {"NoSuchKey", "NotFound"}:
        return True
    text = str(exc)
    return any(token in text for token in ("NoSuchKey", "404", "Not Found", "not found"))

def write_oss_object_bytes(
    *,
    bucket_name: str,
    object_key: str,
    endpoint: str,
    account: Any,
    body: bytes,
    region: str | None = None,
    get_arg: Callable[[str, str | None], str | None] | None = None,
) -> None:
    """Write one OSS object from the DataWorks driver (no MaxFrame STRING tunnel limit)."""
    access_id, secret, token = resolve_dispatch_oss_credentials(account, get_arg=get_arg)
    if oss2 is not None:
        auth = (
            oss2.StsAuth(access_id, secret, token)
            if token
            else oss2.Auth(access_id, secret)
        )
        bucket = oss2.Bucket(auth, endpoint, bucket_name)
        bucket.put_object(object_key, body)
        return
    if oss_v2 is None:
        raise RuntimeError("oss2 or alibabacloud_oss_v2 is required to write OSS objects")
    client = _make_oss_v2_client(
        access_id,
        secret,
        region=region or "cn-shanghai",
        endpoint=endpoint,
        security_token=token or None,
    )
    client.put_object(
        oss_v2.PutObjectRequest(
            bucket=bucket_name,
            key=object_key,
            body=body,
        )
    )

def write_oss_object_text(
    *,
    bucket_name: str,
    object_key: str,
    endpoint: str,
    account: Any,
    text: str,
    region: str | None = None,
    get_arg: Callable[[str, str | None], str | None] | None = None,
) -> None:
    write_oss_object_bytes(
        bucket_name=bucket_name,
        object_key=object_key,
        endpoint=endpoint,
        account=account,
        body=text.encode("utf-8"),
        region=region,
        get_arg=get_arg,
    )

def write_dispatch_to_oss(
    *,
    bucket_name: str,
    object_key: str,
    endpoint: str,
    account: Any,
    payload: dict[str, Any],
    region: str | None = None,
    get_arg: Callable[[str, str | None], str | None] | None = None,
) -> None:
    body = json.dumps(payload, ensure_ascii=False, indent=2).encode("utf-8")
    write_oss_object_bytes(
        bucket_name=bucket_name,
        object_key=object_key,
        endpoint=endpoint,
        account=account,
        body=body,
        region=region,
        get_arg=get_arg,
    )

def read_oss_object_bytes(
    *,
    bucket_name: str,
    object_key: str,
    endpoint: str,
    account: Any,
    region: str | None = None,
    get_arg: Callable[[str, str | None], str | None] | None = None,
) -> bytes | None:
    """Read one OSS object on the DataWorks driver (no MaxFrame 8MB STRING tunnel limit)."""
    access_id, secret, token = resolve_dispatch_oss_credentials(account, get_arg=get_arg)
    if oss2 is not None:
        auth = (
            oss2.StsAuth(access_id, secret, token)
            if token
            else oss2.Auth(access_id, secret)
        )
        bucket = oss2.Bucket(auth, endpoint, bucket_name)
        try:
            return bucket.get_object(object_key).read()
        except oss2.exceptions.NoSuchKey:
            return None
        except oss2.exceptions.NotFound:
            return None
    if oss_v2 is not None:
        client = _make_oss_v2_client(
            access_id,
            secret,
            region=region or "cn-shanghai",
            endpoint=endpoint,
            security_token=token or None,
        )
        try:
            result = client.get_object(
                oss_v2.GetObjectRequest(bucket=bucket_name, key=object_key)
            )
            with result.body as stream:
                return stream.read()
        except Exception as exc:
            if _is_oss_object_missing(exc):
                return None
            raise
    raise RuntimeError("oss2 or alibabacloud_oss_v2 is required to read OSS objects")

def read_oss_object_text(
    *,
    bucket_name: str,
    object_key: str,
    endpoint: str,
    account: Any,
    region: str | None = None,
    get_arg: Callable[[str, str | None], str | None] | None = None,
) -> str | None:
    raw = read_oss_object_bytes(
        bucket_name=bucket_name,
        object_key=object_key,
        endpoint=endpoint,
        account=account,
        region=region,
        get_arg=get_arg,
    )
    if raw is None:
        return None
    return raw.decode("utf-8")

def read_oss_json_object(
    *,
    bucket_name: str,
    object_key: str,
    endpoint: str,
    account: Any,
    region: str | None = None,
    get_arg: Callable[[str, str | None], str | None] | None = None,
) -> dict[str, Any] | None:
    text = read_oss_object_text(
        bucket_name=bucket_name,
        object_key=object_key,
        endpoint=endpoint,
        account=account,
        region=region,
        get_arg=get_arg,
    )
    if text is None:
        return None
    loaded = json.loads(text)
    return loaded if isinstance(loaded, dict) else None

def read_dispatch_from_oss(
    *,
    bucket_name: str,
    object_key: str,
    endpoint: str,
    account: Any,
    region: str | None = None,
    get_arg: Callable[[str, str | None], str | None] | None = None,
) -> dict[str, Any] | None:
    raw = read_oss_object_bytes(
        bucket_name=bucket_name,
        object_key=object_key,
        endpoint=endpoint,
        account=account,
        region=region,
        get_arg=get_arg,
    )
    if raw is None:
        return None
    loaded = json.loads(raw.decode("utf-8"))
    return loaded if isinstance(loaded, dict) else None

def write_dispatch_to_mc(
    client: Any,
    table_prefix: str,
    *,
    ds: str,
    payload: dict[str, Any],
) -> None:
    """Persist dispatch payload for the ODPS SQL assignment node (``job0_dispatch_out``)."""
    table_name = f"{table_prefix}dispatch_staging"
    row = {
        "action": str(payload.get("action") or ""),
        "reason": str(payload.get("reason") or ""),
        "clip_id": str(payload.get("clip_id") or ""),
        "run_id": str(payload.get("run_id") or ""),
        "clip_dir_name": str(payload.get("clip_dir_name") or ""),
        "bag_oss_key": str(payload.get("bag_oss_key") or ""),
        "dispatched_at": str(payload.get("dispatched_at") or utc_now_iso()),
    }
    sql = (
        f"INSERT OVERWRITE TABLE {table_name} PARTITION (ds={_sql_string_literal(ds)}) "
        f"SELECT "
        f"{_sql_string_literal(row['action'])}, "
        f"{_sql_string_literal(row['reason'])}, "
        f"{_sql_string_literal(row['clip_id'])}, "
        f"{_sql_string_literal(row['run_id'])}, "
        f"{_sql_string_literal(row['clip_dir_name'])}, "
        f"{_sql_string_literal(row['bag_oss_key'])}, "
        f"{_sql_string_literal(row['dispatched_at'])}"
    )
    client.execute_sql(sql).wait_for_success()

def merge_taxonomy_into_dispatch(
    payload: dict[str, Any],
    taxonomy: dict[str, Any],
) -> dict[str, Any]:
    merged = dict(payload)
    for key in ("taxonomy_version_id", "taxonomy_version_code", "taxonomy_oss_key"):
        value = taxonomy.get(key)
        if value:
            merged[key] = str(value)
    return merged

def load_taxonomy_latest_from_oss(
    *,
    bucket_name: str,
    endpoint: str,
    account: Any,
    region: str | None = None,
    get_arg: Callable[[str, str | None], str | None] | None = None,
    object_key: str = TAXONOMY_LATEST_OSS_KEY,
) -> dict[str, Any] | None:
    return read_oss_json_object(
        bucket_name=bucket_name,
        object_key=object_key,
        endpoint=endpoint,
        account=account,
        region=region,
        get_arg=get_arg,
    )

def attach_taxonomy_to_dispatch_payload(
    payload: dict[str, Any],
    *,
    bucket_name: str,
    endpoint: str,
    account: Any,
    region: str | None = None,
    get_arg: Callable[[str, str | None], str | None] | None = None,
) -> dict[str, Any]:
    taxonomy = load_taxonomy_latest_from_oss(
        bucket_name=bucket_name,
        endpoint=endpoint,
        account=account,
        region=region,
        get_arg=get_arg,
    )
    if not taxonomy:
        return payload
    return merge_taxonomy_into_dispatch(payload, taxonomy)

def dispatch_payload_from_json(raw: str) -> dict[str, Any] | None:
    text = (raw or "").strip()
    if not text or is_unresolved_dw_placeholder(text):
        return None
    try:
        loaded = json.loads(text)
    except json.JSONDecodeError:
        return None
    return loaded if isinstance(loaded, dict) else None

def log_dataworks_args(*, label: str = "resolve_pipeline_context") -> None:
    """Print how DataWorks injected scheduler / node-context params (diagnostic)."""
    try:
        node_args = args  # type: ignore[name-defined]
    except NameError:
        node_args = {}
    keys = sorted(node_args.keys()) if isinstance(node_args, dict) else []
    print(
        f"{label}: args_keys={keys} "
        f"SKYNET_TASK_INPUT={os.environ.get('SKYNET_TASK_INPUT', '')}"
    )

def _idle_context(*, action: str, reason: str, source: str) -> dict[str, Any]:
    return {
        "should_run": False,
        "action": action or "idle",
        "reason": reason,
        "clip_id": "",
        "run_id": "",
        "clip_dir_name": "",
        "bag_oss_key": "",
        "source": source,
    }

def _run_context(payload: dict[str, Any], *, source: str) -> dict[str, Any]:
    clip_id = str(payload.get("clip_id") or "").strip()
    run_id = str(payload.get("run_id") or "").strip()
    if not clip_id or not run_id:
        raise ValueError(f"Invalid dispatch payload (missing clip_id/run_id): {payload!r}")
    ctx: dict[str, Any] = {
        "should_run": True,
        "action": "run",
        "clip_id": clip_id,
        "run_id": run_id,
        "clip_dir_name": str(payload.get("clip_dir_name") or "").strip(),
        "bag_oss_key": str(payload.get("bag_oss_key") or "").strip(),
        "reason": str(payload.get("reason") or ""),
        "source": source,
    }
    for key in ("taxonomy_version_id", "taxonomy_version_code", "taxonomy_oss_key", "pipeline_version"):
        value = payload.get(key)
        if value:
            ctx[key] = str(value)
    return ctx

def _load_dispatch_from_oss(
    get_arg: Callable[[str, str | None], str | None],
    *,
    oss_account: Any,
    oss_bucket: str | None,
    oss_endpoint: str | None,
) -> dict[str, Any] | None:
    dispatch_key = (
        resolve_node_param("dispatch_oss_key", get_arg, DEFAULT_DISPATCH_OSS_KEY)
        or DEFAULT_DISPATCH_OSS_KEY
    ).strip()
    bucket = (oss_bucket or resolve_node_param("oss_bucket", get_arg, "") or "").strip()
    if not bucket:
        return None
    region = resolve_node_param("cloud_region", get_arg, "cn_shanghai") or "cn_shanghai"
    endpoint = (oss_endpoint or resolve_node_param("oss_endpoint", get_arg, "") or "").strip()
    if not endpoint:
        endpoint = resolve_oss_http_endpoint(region, get_arg=get_arg)
    return read_dispatch_from_oss(
        bucket_name=bucket,
        object_key=dispatch_key,
        endpoint=endpoint,
        account=oss_account,
        region=region,
        get_arg=get_arg,
    )

def resolve_pipeline_context(
    get_arg: Callable[[str, str | None], str | None],
    *,
    odps_client: Any | None = None,
    oss_account: Any | None = None,
    oss_endpoint: str | None = None,
    oss_bucket: str | None = None,
) -> dict[str, Any]:
    """Resolve clip_id/run_id from node args (debug) or OSS dispatch manifest (primary)."""
    log_dataworks_args()

    action = (resolve_node_param("action", get_arg, "") or "").strip().lower()
    clip_id = (resolve_node_param("clip_id", get_arg, "") or "").strip()
    run_id = (resolve_node_param("run_id", get_arg, "") or "").strip()
    clip_dir_name = (resolve_node_param("clip_dir_name", get_arg, "") or "").strip()
    bag_oss_key = (resolve_node_param("bag_oss_key", get_arg, "") or "").strip()

    if action == "idle":
        return _idle_context(
            action="idle",
            reason=(resolve_node_param("reason", get_arg, "idle") or "idle").strip(),
            source="node_params",
        )

    if clip_id and not run_id:
        run_id = str(uuid.uuid4())
    if clip_id and run_id:
        return {
            "should_run": True,
            "action": "run",
            "clip_id": clip_id,
            "run_id": run_id,
            "clip_dir_name": clip_dir_name,
            "bag_oss_key": bag_oss_key,
            "source": "node_params",
        }

    dispatch_key = (
        resolve_node_param("dispatch_oss_key", get_arg, DEFAULT_DISPATCH_OSS_KEY)
        or DEFAULT_DISPATCH_OSS_KEY
    ).strip()
    bucket = (oss_bucket or resolve_node_param("oss_bucket", get_arg, "") or "").strip()

    if oss_account and bucket:
        region = resolve_node_param("cloud_region", get_arg, "cn_shanghai") or "cn_shanghai"
        endpoint_for_log = resolve_oss_http_endpoint(
            region,
            get_arg=get_arg,
            explicit_endpoint=oss_endpoint,
        )
        print(
            f"resolve_pipeline_context: no clip_id in args; reading OSS "
            f"oss://{bucket}/{dispatch_key} via {endpoint_for_log}"
        )
        payload = _load_dispatch_from_oss(
            get_arg,
            oss_account=oss_account,
            oss_bucket=bucket,
            oss_endpoint=oss_endpoint,
        )
        if payload:
            print(f"resolve_pipeline_context: loaded dispatch from OSS (action={payload.get('action')})")
            oss_action = str(payload.get("action") or "").strip().lower()
            if oss_action != "run":
                return _idle_context(
                    action=oss_action or "idle",
                    reason=str(payload.get("reason") or "idle"),
                    source="dispatch_oss",
                )
            return _run_context(payload, source="dispatch_oss")

    dispatch_json = (
        resolve_node_param("dispatch_json", get_arg, "")
        or resolve_node_param("outputs", get_arg, "")
        or ""
    ).strip()
    json_payload = dispatch_payload_from_json(dispatch_json)
    if json_payload:
        oss_action = str(json_payload.get("action") or "").strip().lower()
        if oss_action != "run":
            return _idle_context(
                action=oss_action or "idle",
                reason=str(json_payload.get("reason") or "idle"),
                source="dispatch_json",
            )
        return _run_context(json_payload, source="dispatch_json")

    raw_task_input = (os.environ.get("SKYNET_TASK_INPUT") or "").strip()
    pyodps_args = read_pyodps_args()
    if not bucket or not oss_account:
        raise ValueError(
            "clip_id/run_id empty: set node params for manual run, or ensure "
            "oss_bucket is configured and job0_dispatch ran first"
        )
    if raw_task_input and "${" in raw_task_input:
        raise ValueError(
            "Dispatch OSS manifest missing and node context unresolved "
            f"(SKYNET_TASK_INPUT={raw_task_input}, args_keys={sorted(pyodps_args.keys())}). "
            "Run job0_dispatch_node first (writes "
            f"oss://{bucket}/{dispatch_key}), then job1_parse in the same workflow. "
            "Do not rely on PyODPS node output params for clip_id; remove write_dispatch_oss=false."
        )
    raise ValueError(
        f"Dispatch OSS manifest missing: oss://{bucket}/{dispatch_key}. "
        "Run job0_dispatch_node in the same workflow before downstream nodes."
    )

def exit_if_pipeline_idle(ctx: dict[str, Any], *, node_name: str = "") -> bool:
    """Print idle marker and return True if caller should exit main() successfully."""
    if ctx.get("should_run"):
        return False
    label = f" {node_name}" if node_name else ""
    print(
        f"PIPELINE_IDLE{label}: action={ctx.get('action')} reason={ctx.get('reason')} "
        f"(skip downstream work until next schedule)"
    )
    return True
# === END pipeline_dispatch.py ===

# === BEGIN sdk_dpe_common.py (auto-bundled) ===
# =============================================================================
# SDK DPE 节点共享：Driver 批量编排 + DPE UDF 装饰器
# =============================================================================

import json
import os
from typing import Any, Callable

import pandas as pd

def get_dw_arg(name: str, default: str | None = None) -> str | None:
    try:
        value = args.get(name)  # type: ignore[name-defined]
    except NameError:
        value = None
    if value is None or str(value).strip() == "":
        return default
    return str(value).strip()

def require_dw_arg(name: str) -> str:
    value = get_dw_arg(name)
    if not value:
        raise ValueError(f"Missing required parameter: {name}")
    return value

def get_dw_int_arg(name: str, default: int) -> int:
    value = get_dw_arg(name)
    return default if value is None else int(value)

def get_dw_float_arg(name: str, default: float) -> float:
    value = get_dw_arg(name)
    return default if value is None else float(value)

def apply_dpe_runtime_settings(dpe_image: str | None) -> None:
    from maxframe.config import options as mf_options

    sql_settings = dict(mf_options.sql.settings or {})
    sql_settings["odps.sql.python.version"] = "cp311"
    if dpe_image:
        sql_settings["odps.session.image"] = dpe_image
    mf_options.sql.settings = sql_settings

def configure_dpe_engine() -> None:
    from maxframe.config import options as mf_options

    mf_options.dag.settings = {
        "engine_order": ["DPE"],
        "unavailable_engines": ["MCSQL", "SPE"],
    }
    mf_options.local_execution.enabled = False

def oss_internal_url(region: str, bucket: str, prefix: str) -> str:
    host = f"oss-{region}-internal.aliyuncs.com"
    base = f"oss://{bucket}.{host}"
    if prefix:
        return f"{base}/{prefix.strip('/')}/"
    return f"{base}/"

def storage_options(role_arn: str | None, account: Any) -> dict[str, str]:
    if role_arn:
        return {"oss_role_arn": role_arn}
    return {
        "oss_access_key_id": account.access_id,
        "oss_access_key_secret": account.secret_access_key,
    }

def work_items_to_job_rows(work_items: list[dict[str, Any]]) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for item in work_items:
        bag_oss_key = str(item.get("bag_oss_key") or "").strip()
        run_relpath = str(item.get("run_relpath") or "").strip()
        clip_id = str(item.get("clip_id") or "").strip()
        run_id = str(item.get("run_id") or "").strip()
        if not clip_id or not run_id or not run_relpath:
            raise ValueError(f"invalid batch item: {item!r}")
        row = {
            "clip_id": clip_id,
            "run_id": run_id,
            "run_relpath": run_relpath,
        }
        if bag_oss_key:
            row["bag_oss_key"] = bag_oss_key
        rows.append(row)
    return rows

def make_batch_input_df(job_rows: list[dict[str, str]], dpe_parallel: int):
    import maxframe.dataframe as md

    if not job_rows:
        raise ValueError("job_rows empty")
    input_df = md.DataFrame(pd.DataFrame(job_rows))
    parallel = min(max(int(dpe_parallel or 1), 1), len(job_rows))
    if parallel > 1:
        input_df = input_df.mf.rebalance(num_partitions=parallel)
    return input_df, parallel

def _set_env_from_arg(env: dict[str, str], env_name: str, arg_name: str, *, default: str | None = None) -> None:
    if env_name in env and str(env[env_name]).strip():
        return
    try:
        value = get_dw_arg(arg_name, default)
    except NameError:
        value = default
    if value is not None and str(value).strip():
        env[env_name] = str(value).strip()

def collect_sdk_env_for_dpe(account: Any | None = None) -> dict[str, str]:
    """Driver 收集工作流参数 → DPE UDF 内 os.environ（仅 oms_multimodal import）。"""
    backend_raw = (get_dw_arg("model_backend") or "mc").strip().lower()
    backend = "mc" if backend_raw == "mc" else "api"
    env: dict[str, str] = {"MODEL_BACKEND": backend}
    for env_name, arg_name in (
        ("OMNI_MODEL", "omni_model"),
        ("ASR_MODEL", "asr_model"),
        ("EMBEDDING_MODEL", "embedding_model"),
        ("EMBEDDING_DIMENSION", "embedding_dimension"),
        ("DASHSCOPE_API_KEY", "dashscope_api_key"),
        ("DASHSCOPE_WORKSPACE_ID", "dashscope_workspace_id"),
        ("DASHSCOPE_REGION", "dashscope_region"),
    ):
        _set_env_from_arg(env, env_name, arg_name)
    if backend == "mc":
        for env_name, arg_name, default in (
            ("MC_MODELSET_PROJECT", "mc_modelset_project", "bigdata_public_modelset"),
            ("MC_OMNI_FALLBACK_MODEL", "mc_omni_fallback_model", None),
            ("MC_CLOUD_REGION", "cloud_region", "cn_shanghai"),
            ("MC_OSS_BUCKET", "oss_bucket", None),
            ("OSS_BUCKET", "oss_bucket", None),
            ("MC_DPE_IMAGE", "dpe_image", None),
            ("DPE_IMAGE", "dpe_image", None),
            ("MC_AI_CU_QUOTA_NAME", "ai_cu_quota_name", None),
            ("AI_CU_QUOTA_NAME", "ai_cu_quota_name", None),
            ("MC_AI_GU_QUOTA_NAME", "ai_gu_quota_name", None),
            ("AI_GU_QUOTA_NAME", "ai_gu_quota_name", None),
            ("MC_TOTAL_RPM_LIMIT", "total_rpm_limit", None),
            ("MC_REQUEST_TIMEOUT_SEC", "request_timeout", None),
            ("MC_AI_MEMORY", "ai_memory", None),
            ("MC_IMAGE_MODE", "mc_image_mode", None),
            ("OSS_VL_ACCESS_KEY_ID", "oss_vl_access_key_id", None),
            ("OSS_VL_ACCESS_KEY_SECRET", "oss_vl_access_key_secret", None),
            ("MC_OSS_ACCESS_KEY_ID", "oss_vl_access_key_id", None),
            ("MC_OSS_ACCESS_KEY_SECRET", "oss_vl_access_key_secret", None),
        ):
            _set_env_from_arg(env, env_name, arg_name, default=default)
        if account is not None:
            env.setdefault("ODPS_ACCESS_ID", str(getattr(account, "access_id", "") or ""))
            env.setdefault(
                "ODPS_ACCESS_KEY",
                str(getattr(account, "secret_access_key", "") or getattr(account, "access_key_secret", "") or ""),
            )
            env.setdefault("ODPS_PROJECT", str(getattr(account, "project", "") or ""))
            env.setdefault("ODPS_ENDPOINT", str(getattr(account, "endpoint", "") or ""))
    return env

def wrap_dpe_udf(
    row_fn: Callable,
    *,
    dpe_cpu: int,
    dpe_memory: int,
    oss_mount_url: str,
    mount_path: str,
    storage_options_dict: dict[str, str],
):
    from maxframe.udf import with_fs_mount, with_running_options

    wrapped = with_running_options(engine="dpe", cpu=dpe_cpu, memory=dpe_memory)(row_fn)
    return with_fs_mount(oss_mount_url, mount_path, storage_options=storage_options_dict)(wrapped)

def run_dpe_batch_apply(
    odps_entry: Any,
    input_df: Any,
    udf: Callable,
    output_dtypes: dict[str, str],
) -> pd.DataFrame:
    from maxframe.session import new_session

    session = new_session(odps_entry)
    try:
        print(f"Logview: {session.get_logview_address()}")
        result_df = input_df.apply(
            udf,
            axis=1,
            output_type="dataframe",
            result_type="expand",
            dtypes=output_dtypes,
            skip_infer=True,
        )
        result = result_df.execute().fetch()
        if result.empty:
            raise RuntimeError("DPE batch apply returned no rows")
        return result
    except Exception:
        print(f"Logview: {session.get_logview_address()}")
        raise
    finally:
        session.destroy()

def print_batch_summary(capability: str, result: pd.DataFrame, *, parallel: int) -> None:
    summaries = []
    for _, row in result.iterrows():
        item = row.to_dict()
        summaries.append(item)
        print(
            f"BATCH_DONE clip_id={item.get('clip_id')} run_id={item.get('run_id')} "
            f"capability={capability}"
        )
    print(
        json.dumps(
            {
                "ok": True,
                "capability": capability,
                "batch_size": len(summaries),
                "parallel": parallel,
                "items": summaries,
            },
            ensure_ascii=False,
            default=str,
        )
    )
    print(f"NEXT_NODE_PARAM batch_size={len(summaries)}")
# === END sdk_dpe_common.py ===

# === BEGIN sdk_mc_ingest.py (auto-bundled) ===
"""Build and execute MaxCompute ingest SQL for one SDK v1 run directory."""

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

SDK_LABELS_JSONL = "labels.jsonl"
SDK_EMBEDDINGS_JSONL = "fusion_embeddings.jsonl"
SDK_RUN_JSON = "run.json"

# Cloud verify_sdk_v1_run / HMI expect these five step_ids (see hmi.config.SDK_PIPELINE_STEP_ORDER).
SDK_PIPELINE_STEPS = (
    "sdk_discover",
    "sdk_infer",
    "sdk_upload",
    "sdk_mc_write",
    "sdk_dispatch",
)

def _utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")

def _sql_literal(value: str) -> str:
    return "'" + str(value).replace("'", "''") + "'"

def _read_jsonl_first(path: Path) -> dict[str, Any]:
    for line in path.read_text(encoding="utf-8").splitlines():
        text = line.strip()
        if text:
            row = json.loads(text)
            if isinstance(row, dict):
                return row
    raise ValueError(f"empty jsonl: {path}")

def _read_json_object(path: Path) -> dict[str, Any]:
    if not path.is_file():
        return {}
    loaded = json.loads(path.read_text(encoding="utf-8"))
    return loaded if isinstance(loaded, dict) else {}

def _labels_to_clip_dict(raw_labels: Any) -> dict[str, Any]:
    if isinstance(raw_labels, str):
        raw_labels = json.loads(raw_labels) if raw_labels else {}
    if not isinstance(raw_labels, dict):
        return {}
    values = raw_labels.get("values")
    if not isinstance(values, dict):
        values = raw_labels
    result: dict[str, Any] = {}
    for key, entry in values.items():
        if isinstance(entry, dict) and "value" in entry:
            result[str(key)] = entry["value"]
        elif isinstance(entry, dict) and entry.get("values") is not None:
            result[str(key)] = str(entry["values"])
        elif entry is None:
            result[str(key)] = None
        else:
            result[str(key)] = str(entry)
    return result

def build_ingest_statements(
    *,
    clip_id: str,
    run_id: str,
    ds: str,
    run_dir: Path,
    table_prefix: str = "aig_sdk__",
    bag_oss_key: str = "",
    now: str | None = None,
) -> list[str]:
    """Return SQL statements for SDK jsonl artifacts without contacting ODPS."""
    run_dir = Path(run_dir)
    label_row = _read_jsonl_first(run_dir / SDK_LABELS_JSONL)
    embed_row = _read_jsonl_first(run_dir / SDK_EMBEDDINGS_JSONL)
    run_doc = _read_json_object(run_dir / SDK_RUN_JSON)

    start_ns = int(label_row.get("start_timestamp_ns") or 0)
    end_ns = int(label_row.get("end_timestamp_ns") or start_ns)
    duration = float(label_row.get("duration_sec") or max(0.0, (end_ns - start_ns) / 1e9))
    labels_json = json.dumps(
        _labels_to_clip_dict(label_row.get("labels") or {}),
        ensure_ascii=False,
    )
    vector = embed_row.get("embedding") or embed_row.get("vector") or []
    vector_json = json.dumps(list(vector), ensure_ascii=False)

    clip_dir_name = str(run_doc.get("source_run_dir") or clip_id)
    effective_bag_key = str(bag_oss_key or run_doc.get("bag_oss_key") or "")
    created_at = now or _utc_now()
    content_hash = clip_id.split(":", 1)[-1][:64]
    p = table_prefix

    statements = [
        f"INSERT INTO TABLE {p}dim_clip "
        f"SELECT {_sql_literal(clip_id)}, {_sql_literal(clip_dir_name)}, "
        f"{_sql_literal(content_hash)}, {_sql_literal(effective_bag_key)}, "
        f"{_sql_literal(run_id)}, 'sdk_v1', {_sql_literal(created_at)}, {_sql_literal(created_at)}",
        f"INSERT INTO TABLE {p}pipeline_run PARTITION (ds={_sql_literal(ds)}) "
        f"SELECT {_sql_literal(run_id)}, {_sql_literal(clip_id)}, 'completed', 'sdk_v1', 'clip', "
        f"{_sql_literal(created_at)}, {_sql_literal(created_at)}, {_sql_literal(created_at)}",
        f"INSERT INTO TABLE {p}clip_parse_summary PARTITION (ds={_sql_literal(ds)}) "
        f"SELECT {_sql_literal(clip_id)}, {_sql_literal(run_id)}, 'output', 'output.bag', "
        f"{end_ns - start_ns}, {duration}, {start_ns}, {end_ns}, 0, {_sql_literal(created_at)}",
        f"INSERT INTO TABLE {p}fact_clip_label PARTITION (ds={_sql_literal(ds)}) "
        f"SELECT {_sql_literal(clip_id)}, {_sql_literal(run_id)}, {_sql_literal(labels_json)}, "
        f"NULL, {_sql_literal(str(label_row.get('model') or ''))}, 'ai', {start_ns}, NULL, "
        f"{_sql_literal(f'clips/{clip_id}/runs/{run_id}/{SDK_LABELS_JSONL}')}, "
        f"{_sql_literal(created_at)}, {_sql_literal(created_at)}",
        f"INSERT INTO TABLE {p}fact_clip_embedding PARTITION (ds={_sql_literal(ds)}) "
        f"SELECT {_sql_literal(clip_id)}, {_sql_literal(run_id)}, {_sql_literal(vector_json)}, "
        f"{len(vector)}, {_sql_literal(str(embed_row.get('model') or ''))}, 'clip_native', "
        f"{_sql_literal(f'clips/{clip_id}/runs/{run_id}/{SDK_EMBEDDINGS_JSONL}')}, "
        f"{_sql_literal(created_at)}, {_sql_literal(created_at)}",
    ]

    asr_text = str(label_row.get("asr_text") or "").strip()
    if asr_text:
        statements.append(
            f"INSERT INTO TABLE {p}fact_audio_segment PARTITION (ds={_sql_literal(ds)}) "
            f"SELECT {_sql_literal(clip_id)}, {_sql_literal(run_id)}, 0, {start_ns}, {end_ns}, "
            f"{_sql_literal(asr_text)}, 1.0, NULL, 'preview/audio.wav'"
        )

    # Mark cloud five-step contract complete for a successful Driver ingest.
    # Partial UDF stages still land as completed once artifacts exist and ingest runs.
    for step_id in SDK_PIPELINE_STEPS:
        statements.append(
            f"INSERT INTO TABLE {p}pipeline_step PARTITION (ds={_sql_literal(ds)}) "
            f"SELECT {_sql_literal(run_id)}, {_sql_literal(step_id)}, 'completed', "
            f"{_sql_literal(created_at)}, {_sql_literal(created_at)}, NULL"
        )
    return statements

def ingest_sdk_run(
    odps: Any,
    *,
    clip_id: str,
    run_id: str,
    ds: str,
    run_dir: Path,
    table_prefix: str = "aig_sdk__",
    bag_oss_key: str = "",
) -> None:
    """Execute all ingest statements for one successful SDK run."""
    statements = build_ingest_statements(
        clip_id=clip_id,
        run_id=run_id,
        ds=ds,
        run_dir=run_dir,
        table_prefix=table_prefix,
        bag_oss_key=bag_oss_key,
    )
    for sql in statements:
        odps.execute_sql(sql)
        print("OK", sql[:80], "...")
# === END sdk_mc_ingest.py ===

# === BEGIN sdk_pipeline_driver_lib.py (auto-bundled) ===
# pipeline/dataworks/sdk_pipeline_driver_lib.py

import uuid
from typing import Any

try:
    from oms_multimodal.capabilities.stages import DRIVER_STAGES, UDF_STAGES, parse_stages
except ImportError:  # pragma: no cover - DW paste without path
    DRIVER_STAGES = frozenset({"discover", "mc_write", "dispatch"})
    UDF_STAGES = frozenset({"extract", "asr", "preview", "label", "embed", "upload"})

    def parse_stages(raw: str | None) -> frozenset[str]:
        if not raw or not str(raw).strip():
            return DRIVER_STAGES | UDF_STAGES
        parts = {t.strip().lower() for t in str(raw).split(",") if t.strip()}
        return frozenset(parts)

def split_stages(raw: str | None) -> tuple[frozenset[str], frozenset[str]]:
    stages = parse_stages(raw)
    return stages & DRIVER_STAGES, stages & UDF_STAGES

def content_hash_to_clip_id(hex_digest: str) -> str:
    digest = hex_digest.strip().lower().removeprefix("sha256:")
    return f"sha256:{digest}"

def filter_already_completed(
    bags: list[dict[str, Any]],
    *,
    completed_clip_ids: set[str],
    force_rerun: bool,
) -> list[dict[str, Any]]:
    if force_rerun:
        return list(bags)
    return [bag for bag in bags if str(bag["clip_id"]) not in completed_clip_ids]

def trim_discovered_bags(
    bags: list[dict[str, Any]],
    *,
    max_bags: int | None,
) -> list[dict[str, Any]]:
    ordered = sorted(bags, key=lambda bag: str(bag["bag_oss_key"]))
    if max_bags is None:
        return ordered
    return ordered[: max(0, max_bags)]

def make_run_id() -> str:
    return str(uuid.uuid4())

def run_oss_prefix_from_relpath(run_relpath: str) -> str:
    return f"{str(run_relpath).rstrip('/')}/"

def build_job_rows(bags: list[dict[str, Any]], *, ds: str) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for bag in bags:
        clip_id = str(bag["clip_id"]).strip()
        run_id = str(bag["run_id"]).strip()
        bag_oss_key = str(bag["bag_oss_key"]).strip()
        run_relpath = f"clips/{clip_id}/runs/{run_id}"
        rows.append(
            {
                "clip_id": clip_id,
                "run_id": run_id,
                "bag_oss_key": bag_oss_key,
                "run_relpath": run_relpath,
                "ds": ds,
            }
        )
    return rows

def chunk_output_dtypes() -> dict[str, str]:
    return {
        "clip_id": "string",
        "run_id": "string",
        "bag_oss_key": "string",
        "ds": "string",
        "ok": "boolean",
        "error": "string",
        "stages_done": "string",
        "run_relpath": "string",
        "labels_relpath": "string",
        "embeddings_relpath": "string",
        "videos_relpath": "string",
        "preview_ok": "boolean",
    }

def row_success_status(errors: list[dict[str, str]], *, require_files: bool = False) -> bool:
    if errors:
        return False
    return True

def batch_summary(result_rows: list[dict[str, Any]]) -> dict[str, Any]:
    def _ok(r: dict[str, Any]) -> bool:
        v = r.get("ok")
        return v is True or v == 1 or str(v).lower() == "true"

    ok_rows = [r for r in result_rows if _ok(r)]
    fail_rows = [r for r in result_rows if not _ok(r)]
    return {
        "total": len(result_rows),
        "ok_count": len(ok_rows),
        "fail_count": len(fail_rows),
        "ok_clip_ids": [str(r.get("clip_id")) for r in ok_rows],
        "failures": [
            {"clip_id": str(r.get("clip_id")), "error": str(r.get("error") or "")[:500]}
            for r in fail_rows
        ],
    }
# === END sdk_pipeline_driver_lib.py ===

# === BEGIN sdk_pipeline_driver_node.py ===
# =============================================================================
# DataWorks PyODPS3: SDK single-driver (discover + pipeline apply_chunk)
# Production discovery uses two apply_chunk passes in this one Driver node:
# (1) hash bag bytes on the OSS mount; (2) run selected SDK pipeline stages.
# =============================================================================

from datetime import datetime, timezone
import json
from pathlib import Path
import re
from typing import Any

import pandas as pd

def _explicit_bag_from_args() -> list[dict[str, str]] | None:
    bag_oss_key = get_dw_arg("bag_oss_key")
    clip_id = get_dw_arg("clip_id")
    run_id = get_dw_arg("run_id")
    explicit_values = (bag_oss_key, clip_id, run_id)
    if any(explicit_values):
        if not all(explicit_values):
            raise ValueError("bag_oss_key, clip_id, and run_id must be provided together")
        return [
            {
                "bag_oss_key": str(bag_oss_key),
                "clip_id": str(clip_id),
                "run_id": str(run_id),
            }
        ]
    return None

def _debug_bag_keys_from_args() -> list[str]:
    raw_keys = get_dw_arg("bag_oss_keys", "") or ""
    return [
        key.strip()
        for key in re.split(r"[\r\n,]+", raw_keys)
        if key.strip().lower().endswith(".bag")
    ]

def _list_bag_keys_from_oss(
    account: Any,
    *,
    oss_bucket: str,
    cloud_region: str,
) -> list[str]:
    from oss_v2_dw import iter_object_keys, make_oss_client

    client = make_oss_client(
        access_key_id=str(account.access_id),
        access_key_secret=str(account.secret_access_key),
        region=cloud_region,
        endpoint=get_dw_arg("oss_endpoint"),
    )
    return list(
        iter_object_keys(
            client,
            bucket=oss_bucket,
            prefix=get_dw_arg("scan_prefix", "rosbags/") or "rosbags/",
            suffix=".bag",
            max_count=int(get_dw_arg("max_scan", "1000") or "1000"),
        )
    )

def _hash_chunk_output_dtypes() -> dict[str, str]:
    return {
        "clip_id": "string",
        "bag_oss_key": "string",
        "content_hash": "string",
    }

def _build_hash_chunk_udf(
    *,
    dpe_cpu: int,
    dpe_memory: int,
    oss_mount_url: str,
    mount_path: str,
    storage_options_dict: dict[str, str],
):
    def _hash_chunk(df: pd.DataFrame) -> pd.DataFrame:
        from pathlib import Path
        import hashlib

        rows_out: list[dict[str, str]] = []
        for _, row in df.iterrows():
            bag_oss_key = str(row["bag_oss_key"])
            hasher = hashlib.sha256()
            with (Path(mount_path) / bag_oss_key).open("rb") as bag_file:
                while True:
                    block = bag_file.read(1024 * 1024)
                    if not block:
                        break
                    hasher.update(block)
            content_hash = hasher.hexdigest()
            rows_out.append(
                {
                    "clip_id": f"sha256:{content_hash}",
                    "bag_oss_key": bag_oss_key,
                    "content_hash": content_hash,
                }
            )
        return pd.DataFrame(rows_out)

    return wrap_dpe_udf(
        _hash_chunk,
        dpe_cpu=dpe_cpu,
        dpe_memory=dpe_memory,
        oss_mount_url=oss_mount_url,
        mount_path=mount_path,
        storage_options_dict=storage_options_dict,
    )

def _completed_clip_ids(
    client: Any,
    *,
    table_prefix: str,
    clip_ids: list[str],
) -> set[str]:
    """Find clips whose active SDK run is completed; failures are handled by caller."""
    completed: set[str] = set()
    for start in range(0, len(clip_ids), 50):
        batch = clip_ids[start : start + 50]
        quoted = ",".join("'" + cid.replace("'", "''") + "'" for cid in batch)
        sql = (
            f"SELECT d.clip_id FROM {table_prefix}dim_clip d "
            f"JOIN {table_prefix}pipeline_run r "
            "ON d.clip_id = r.clip_id AND d.active_run_id = r.run_id "
            f"WHERE d.clip_id IN ({quoted}) AND r.status = 'completed'"
        )
        with client.execute_sql(sql).open_reader() as reader:
            for record in reader:
                completed.add(str(record[0]))
    return completed

def _build_pipeline_chunk_udf(
    *,
    dpe_cpu: int,
    dpe_memory: int,
    oss_mount_url: str,
    mount_path: str,
    storage_options_dict: dict[str, str],
    sdk_env: dict[str, str],
    udf_stages_frozen: frozenset[str],
    clip_min_sec: float,
    clip_max_sec: float,
    sample_fps: float,
    model_backend: str,
    cleanup_work: bool,
):
    def _pipeline_chunk(df: pd.DataFrame) -> pd.DataFrame:
        import os
        from pathlib import Path

        from oms_multimodal import ClipConfig, OmsMultimodalClient, run_stages

        for key, value in sdk_env.items():
            if value:
                os.environ[key] = str(value)

        rows_out: list[dict[str, Any]] = []
        for _, row in df.iterrows():
            clip_id = str(row["clip_id"])
            run_id = str(row["run_id"])
            bag_oss_key = str(row["bag_oss_key"])
            run_relpath = str(row["run_relpath"])
            ds = str(row["ds"])
            try:
                bag_path = Path(mount_path) / bag_oss_key
                run_out = Path(mount_path) / run_relpath
                run_out.mkdir(parents=True, exist_ok=True)
                client = OmsMultimodalClient(
                    work_dir=run_out / "_sdk_work",
                    load_dotenv=False,
                )
                try:
                    ctx = client.make_run_context(
                        run_out,
                        media_mode="local",
                        clip_id=clip_id,
                        run_id=run_id,
                    )
                    result = run_stages(
                        ctx,
                        bag_path,
                        client,
                        stages=udf_stages_frozen,
                        clip_config=ClipConfig(
                            min_sec=clip_min_sec,
                            max_sec=clip_max_sec,
                            sample_fps=sample_fps,
                        ),
                        bag_oss_key=bag_oss_key,
                        ds=ds,
                        model_backend=model_backend,
                        cleanup_work=cleanup_work,
                    )
                finally:
                    close = getattr(client, "close", None)
                    if callable(close):
                        close()

                # Any capability error blocks Driver-side mc_write for this row.
                ok = len(result.errors) == 0
                error = str(result.errors[0])[:500] if result.errors else ""
                rows_out.append(
                    {
                        "clip_id": clip_id,
                        "run_id": run_id,
                        "bag_oss_key": bag_oss_key,
                        "ds": ds,
                        "ok": ok,
                        "error": error,
                        "stages_done": ",".join(result.stages_done),
                        "run_relpath": run_relpath,
                        "labels_relpath": f"{run_relpath}/labels.jsonl",
                        "embeddings_relpath": f"{run_relpath}/fusion_embeddings.jsonl",
                        "videos_relpath": f"{run_relpath}/clip_videos.jsonl",
                        "preview_ok": bool(result.preview_ok),
                    }
                )
            except Exception as exc:  # noqa: BLE001
                rows_out.append(
                    {
                        "clip_id": clip_id,
                        "run_id": run_id,
                        "bag_oss_key": bag_oss_key,
                        "ds": ds,
                        "ok": False,
                        "error": f"{type(exc).__name__}: {exc}"[:500],
                        "stages_done": "",
                        "run_relpath": run_relpath,
                        "labels_relpath": f"{run_relpath}/labels.jsonl",
                        "embeddings_relpath": f"{run_relpath}/fusion_embeddings.jsonl",
                        "videos_relpath": f"{run_relpath}/clip_videos.jsonl",
                        "preview_ok": False,
                    }
                )
        return pd.DataFrame(rows_out)

    return wrap_dpe_udf(
        _pipeline_chunk,
        dpe_cpu=dpe_cpu,
        dpe_memory=dpe_memory,
        oss_mount_url=oss_mount_url,
        mount_path=mount_path,
        storage_options_dict=storage_options_dict,
    )

def main() -> None:
    stages_raw = get_dw_arg("stages")
    driver_stages, udf_stages = split_stages(stages_raw)
    ds = get_dw_arg("ds") or datetime.now(timezone.utc).strftime("%Y%m%d")
    account = o.account  # type: ignore[name-defined]
    oss_bucket = get_dw_arg("oss_bucket")
    if not oss_bucket:
        raise ValueError("Missing required parameter: oss_bucket")
    cloud_region = get_dw_arg("cloud_region", "cn_shanghai") or "cn_shanghai"
    dpe_image = (get_dw_arg("dpe_image") or "").strip()
    if not dpe_image:
        raise ValueError("Missing required parameter: dpe_image")
    mount_path = get_dw_arg("mount_path", get_dw_arg("dpe_mount_path", "/mnt/oss")) or "/mnt/oss"
    batch_rows = int(get_dw_arg("batch_rows", "1") or "1")
    if batch_rows < 1:
        raise ValueError("batch_rows must be >= 1")
    hash_batch_rows = int(get_dw_arg("hash_batch_rows", "32") or "32")
    if hash_batch_rows < 1:
        raise ValueError("hash_batch_rows must be >= 1")
    dpe_cpu = int(get_dw_arg("dpe_cpu", "4") or "4")
    dpe_memory = int(get_dw_arg("dpe_memory_gb", "16") or "16")
    clip_min_sec = get_dw_float_arg("clip_min_sec", 15.0)
    clip_max_sec = get_dw_float_arg("clip_max_sec", 20.0)
    sample_fps = get_dw_float_arg("sample_fps", 1.0)
    cleanup_work = (get_dw_arg("cleanup_work", "false") or "false").lower() in {
        "1",
        "true",
        "yes",
        "on",
    }
    sdk_env = collect_sdk_env_for_dpe(account)
    # Workflow secret args override account-derived values; project/endpoint
    # fall back to the current Driver ODPS entry when available.
    odps_env_values = {
        "ODPS_ACCESS_ID": get_dw_arg("odps_access_id"),
        "ODPS_ACCESS_KEY": get_dw_arg("odps_access_key"),
        "ODPS_PROJECT": get_dw_arg("odps_project") or getattr(o, "project", ""),  # type: ignore[name-defined]
        "ODPS_ENDPOINT": get_dw_arg("odps_endpoint") or getattr(o, "endpoint", ""),  # type: ignore[name-defined]
    }
    for env_name, value in odps_env_values.items():
        if value:
            sdk_env[env_name] = str(value)
    model_backend = sdk_env["MODEL_BACKEND"]

    apply_dpe_runtime_settings(dpe_image)
    configure_dpe_engine()

    import maxframe.dataframe as md
    from maxframe.session import new_session

    mount_url = oss_internal_url(
        cloud_region,
        oss_bucket,
        get_dw_arg("oss_mount_prefix", "") or "",
    )
    mount_storage = storage_options(get_dw_arg("oss_ram_role_arn"), account)
    session = new_session(o)  # type: ignore[name-defined]
    try:
        print(f"Logview: {session.get_logview_address()}")
        explicit_bags = _explicit_bag_from_args()
        if explicit_bags is not None:
            discovered_bags: list[dict[str, Any]] = explicit_bags
            print("DEBUG_OVERRIDE: using explicit clip_id/run_id/bag_oss_key")
        else:
            bag_keys = _debug_bag_keys_from_args()
            if not bag_keys:
                bag_keys = _list_bag_keys_from_oss(
                    account,
                    oss_bucket=oss_bucket,
                    cloud_region=cloud_region,
                )
            if not bag_keys:
                raise ValueError(
                    "no bags discovered from OSS; set scan_prefix or bag_oss_keys"
                )
            hash_input_df = md.DataFrame(
                pd.DataFrame([{"bag_oss_key": key} for key in bag_keys])
            )
            hash_udf = _build_hash_chunk_udf(
                dpe_cpu=dpe_cpu,
                dpe_memory=dpe_memory,
                oss_mount_url=mount_url,
                mount_path=mount_path,
                storage_options_dict=mount_storage,
            )
            hash_result = (
                hash_input_df.mf.apply_chunk(
                    hash_udf,
                    batch_rows=hash_batch_rows,
                    output_type="dataframe",
                    dtypes=_hash_chunk_output_dtypes(),
                    skip_infer=True,
                )
                .execute()
                .fetch()
            )
            discovered_bags = [
                {
                    "clip_id": content_hash_to_clip_id(str(row["content_hash"])),
                    "bag_oss_key": str(row["bag_oss_key"]),
                    "content_hash": str(row["content_hash"]),
                }
                for _, row in hash_result.iterrows()
            ]

        force_rerun = (get_dw_arg("force_rerun", "false") or "false").lower() in {
            "1",
            "true",
            "yes",
            "on",
        }
        completed_clip_ids: set[str] = set()
        if not force_rerun:
            table_prefix = (
                get_dw_arg("sdk_table_prefix")
                or get_dw_arg("table_prefix")
                or "aig_sdk__"
            )
            try:
                completed_clip_ids = _completed_clip_ids(
                    o,  # type: ignore[name-defined]
                    table_prefix=table_prefix,
                    clip_ids=[str(bag["clip_id"]) for bag in discovered_bags],
                )
            except Exception as exc:  # noqa: BLE001
                # A first deployment may run before SDK tables exist. Discovery
                # remains usable and mc_write can create/populate them later.
                print(
                    "WARNING: completed-run lookup failed; continuing without skip: "
                    f"{type(exc).__name__}: {exc}"
                )
        runnable_bags = filter_already_completed(
            discovered_bags,
            completed_clip_ids=completed_clip_ids,
            force_rerun=force_rerun,
        )
        max_bags_raw = get_dw_arg("max_bags")
        runnable_bags = trim_discovered_bags(
            runnable_bags,
            max_bags=None if max_bags_raw is None else int(max_bags_raw),
        )
        for bag in runnable_bags:
            bag.setdefault("run_id", make_run_id())
        job_rows = build_job_rows(runnable_bags, ds=ds)
        print(
            "DISCOVERED_ROWS_JSON="
            + json.dumps(
                {
                    "driver_stages": sorted(driver_stages),
                    "hashed_count": len(discovered_bags),
                    "skipped_completed": len(discovered_bags) - len(
                        filter_already_completed(
                            discovered_bags,
                            completed_clip_ids=completed_clip_ids,
                            force_rerun=force_rerun,
                        )
                    ),
                    "items": job_rows,
                },
                ensure_ascii=False,
            )
        )
        if not job_rows:
            print("No runnable bags after completed-run skip/max_bags")
            return
        if not udf_stages:
            print("No UDF stages selected; skipping pipeline apply_chunk")
            return

        input_df = md.DataFrame(pd.DataFrame(job_rows))
        pipeline_udf = _build_pipeline_chunk_udf(
            dpe_cpu=dpe_cpu,
            dpe_memory=dpe_memory,
            oss_mount_url=mount_url,
            mount_path=mount_path,
            storage_options_dict=mount_storage,
            sdk_env=sdk_env,
            udf_stages_frozen=frozenset(udf_stages),
            clip_min_sec=clip_min_sec,
            clip_max_sec=clip_max_sec,
            sample_fps=sample_fps,
            model_backend=model_backend,
            cleanup_work=cleanup_work,
        )
        result = (
            input_df.mf.apply_chunk(
                pipeline_udf,
                batch_rows=batch_rows,
                output_type="dataframe",
                dtypes=chunk_output_dtypes(),
                skip_infer=True,
            )
            .execute()
            .fetch()
        )
        result_rows = [row.to_dict() for _, row in result.iterrows()]
        print(
            "BATCH_SUMMARY_JSON="
            + json.dumps(batch_summary(result_rows), ensure_ascii=False, default=str)
        )
        ok_rows = [
            row
            for row in result_rows
            if row.get("ok") is True
            or row.get("ok") == 1
            or str(row.get("ok")).lower() == "true"
        ]
        postprocess_stages = driver_stages & {"mc_write", "dispatch"}
        if postprocess_stages and not ok_rows:
            print(
                "WARNING: no successful rows; skipping Driver stages "
                + ",".join(sorted(postprocess_stages))
            )

        if "mc_write" in driver_stages:
            table_prefix = (
                get_dw_arg("sdk_table_prefix")
                or get_dw_arg("table_prefix")
                or "aig_sdk__"
            )
            for row in ok_rows:
                ingest_sdk_run(
                    o,  # type: ignore[name-defined]
                    clip_id=str(row["clip_id"]),
                    run_id=str(row["run_id"]),
                    ds=str(row["ds"]),
                    run_dir=Path(mount_path) / str(row["run_relpath"]),
                    table_prefix=table_prefix,
                    bag_oss_key=str(row["bag_oss_key"]),
                )

        if "dispatch" in driver_stages and ok_rows:
            items = [
                {
                    "clip_id": str(row["clip_id"]),
                    "run_id": str(row["run_id"]),
                    "bag_oss_key": str(row["bag_oss_key"]),
                    "ds": str(row["ds"]),
                    "run_relpath": str(row["run_relpath"]),
                    "run_oss_prefix": run_oss_prefix_from_relpath(
                        str(row["run_relpath"])
                    ),
                }
                for row in ok_rows
            ]
            payload: dict[str, Any] = {
                "action": "run",
                "layout_version": "sdk_v1",
                "pipeline_version": "sdk_v1",
                "batch_size": len(items),
                "items": items,
                "run_oss_prefix": items[0]["run_oss_prefix"],
                "dispatched_at": utc_now_iso(),
            }
            if len(items) == 1:
                payload.update(items[0])
            dispatch_key = (
                get_dw_arg("dispatch_oss_key", DEFAULT_DISPATCH_OSS_KEY)
                or DEFAULT_DISPATCH_OSS_KEY
            )
            dispatch_endpoint = resolve_oss_http_endpoint(
                cloud_region,
                get_arg=get_dw_arg,
                explicit_endpoint=get_dw_arg("oss_endpoint"),
            )
            write_dispatch_to_oss(
                bucket_name=oss_bucket,
                object_key=dispatch_key,
                endpoint=dispatch_endpoint,
                account=account,
                payload=payload,
                region=cloud_region,
                get_arg=get_dw_arg,
            )
            print(
                "DISPATCH_JSON="
                + json.dumps(payload, ensure_ascii=False, default=str)
            )
    except Exception:
        print(f"Logview: {session.get_logview_address()}")
        raise
    finally:
        session.destroy()

if __name__ == "__main__":
    main()
# === END sdk_pipeline_driver_node.py ===
