"""OMS Multimodal SDK — Rosbag 多模态打标与融合向量。

Public API::

    from oms_multimodal import OmsMultimodalClient, ClipConfig, AcousticPanelConfig

    client = OmsMultimodalClient(taxonomy_path="oms_label_taxonomy.yaml")
    result = client.process_bag("rosbag/output.bag")
"""
from __future__ import annotations

__version__ = "0.3.3"

from .acoustic_panel import (
    AcousticPanelConfig,
    PanelType,
    compute_mel_matrix,
    mel_matrix_to_feature_text,
    render_acoustic_assets,
    render_acoustic_panel,
    save_mel_matrix,
)
from .bbox import (
    BBox,
    BBoxDetector,
    COCO80_CLASS_NAMES,
    FrameBBoxes,
    NoOpDetector,
    OpenCvFaceDetector,
    OpenCvHaarDetector,
    StubDetector,
    YoloDetector,
    default_element_name,
    draw_bboxes_on_image,
    list_detectors,
    list_yolo_class_catalog,
    resolve_detector,
    resolve_yolo_class_ids,
)
from .asr_client import AsrClient, AsrConfig
from .clip_video import ClipVideoConfig, encode_clip_mp4, render_clip_preview_video
from .client import OmsMultimodalClient
from .config import BagProcessResult, ClientConfig, ClipConfig, ModelBackend, OutputConfig
from .embedding_client import FusionEmbeddingClient
from .resources import (
    bundled_dataworks_doc_path,
    bundled_examples_dir,
    bundled_sdk_doc_path,
    bundled_taxonomy_path,
    resolve_taxonomy_path,
)
from .capabilities import (
    ALL_STAGES,
    CAPABILITY_IDS,
    DRIVER_STAGES,
    STEP_TO_CAPABILITY,
    UDF_STAGES,
    BBoxResult,
    CapabilityPlanner,
    EmbedResult,
    EncodePreviewResult,
    ExtractResult,
    InferFullResult,
    LabelResult,
    MediaInputMode,
    PipelinePlan,
    PlannedCapability,
    RunContext,
    RunRequest,
    StagesResult,
    TranscribeResult,
    annotate_bboxes,
    apply_run_context_to_mc_config,
    embed_clips,
    encode_preview_videos,
    extract_clips,
    infer_full,
    ingest_sources,
    label_clips,
    materialize_preview,
    merge_asr_into_clips,
    parse_stages,
    plan_and_run,
    resolve_encode_variants,
    run_plan,
    run_stages,
    transcribe_clips,
    write_run_json,
)
from .exceptions import ApiError, ConfigurationError, OmsMultimodalError, ParseError
from .omni_client import OmniLabelClient
from .pipeline import LabelEmbeddingPipeline, resolve_bags, write_jsonl
from .rosbag_parser import (
    AudioPayload,
    Clip,
    FramePayload,
    RosbagExtractor,
    TextPayload,
    TopicInfo,
    inspect_bag,
)
from .label_prompt import (
    OMNI_LABEL_PROMPT_FIELD_META,
    default_omni_label_prompt,
    merge_omni_label_prompt,
)
from .model_factory import (
    create_asr_client,
    create_embedding_client,
    create_mc_runtime,
    create_omni_client,
    validate_backend_config,
)
from .mc import McBackendConfig
from .taxonomy import (
    LabelingTaxonomyOptions,
    load_taxonomy,
    normalize_model_labels,
    parse_label_json,
    prepare_taxonomy_for_labeling,
    resolve_labeling_taxonomy_options,
    taxonomy_prompt_block,
)
from .taxonomy_tree import (
    crop_taxonomy,
    crop_taxonomy_for_labeling,
    enum_tree_node,
    format_enum_tree_for_prompt,
    make_enum_tree_schema,
    minimal_enum_tree_example,
    normalize_tree_value,
    tree_depth,
    validate_enum_tree_schema,
)

__all__ = [
    "__version__",
    "ALL_STAGES",
    "AcousticPanelConfig",
    "ApiError",
    "AsrClient",
    "AsrConfig",
    "AudioPayload",
    "BBox",
    "BBoxDetector",
    "BBoxResult",
    "BagProcessResult",
    "bundled_dataworks_doc_path",
    "bundled_examples_dir",
    "bundled_sdk_doc_path",
    "bundled_taxonomy_path",
    "CapabilityPlanner",
    "ClientConfig",
    "Clip",
    "ClipConfig",
    "ClipVideoConfig",
    "ConfigurationError",
    "encode_clip_mp4",
    "FrameBBoxes",
    "FramePayload",
    "CAPABILITY_IDS",
    "DRIVER_STAGES",
    "STEP_TO_CAPABILITY",
    "UDF_STAGES",
    "annotate_bboxes",
    "apply_run_context_to_mc_config",
    "draw_bboxes_on_image",
    "embed_clips",
    "encode_preview_videos",
    "extract_clips",
    "infer_full",
    "ingest_sources",
    "label_clips",
    "materialize_preview",
    "merge_asr_into_clips",
    "NoOpDetector",
    "OpenCvFaceDetector",
    "OpenCvHaarDetector",
    "default_element_name",
    "parse_stages",
    "plan_and_run",
    "PipelinePlan",
    "PlannedCapability",
    "list_detectors",
    "list_yolo_class_catalog",
    "COCO80_CLASS_NAMES",
    "resolve_detector",
    "resolve_yolo_class_ids",
    "resolve_encode_variants",
    "run_plan",
    "run_stages",
    "StubDetector",
    "YoloDetector",
    "transcribe_clips",
    "write_run_json",
    "EmbedResult",
    "EncodePreviewResult",
    "ExtractResult",
    "InferFullResult",
    "LabelResult",
    "MediaInputMode",
    "RunContext",
    "RunRequest",
    "StagesResult",
    "TranscribeResult",
    "FusionEmbeddingClient",
    "LabelEmbeddingPipeline",
    "McBackendConfig",
    "ModelBackend",
    "OmsMultimodalClient",
    "OmsMultimodalError",
    "OmniLabelClient",
    "OutputConfig",
    "PanelType",
    "ParseError",
    "RosbagExtractor",
    "TextPayload",
    "TopicInfo",
    "inspect_bag",
    "LabelingTaxonomyOptions",
    "load_taxonomy",
    "merge_omni_label_prompt",
    "default_omni_label_prompt",
    "OMNI_LABEL_PROMPT_FIELD_META",
    "normalize_model_labels",
    "crop_taxonomy",
    "crop_taxonomy_for_labeling",
    "enum_tree_node",
    "format_enum_tree_for_prompt",
    "make_enum_tree_schema",
    "minimal_enum_tree_example",
    "normalize_tree_value",
    "parse_label_json",
    "prepare_taxonomy_for_labeling",
    "resolve_labeling_taxonomy_options",
    "tree_depth",
    "validate_enum_tree_schema",
    "compute_mel_matrix",
    "create_asr_client",
    "create_embedding_client",
    "create_mc_runtime",
    "create_omni_client",
    "mel_matrix_to_feature_text",
    "render_acoustic_assets",
    "render_acoustic_panel",
    "render_clip_preview_video",
    "resolve_bags",
    "resolve_taxonomy_path",
    "save_mel_matrix",
    "taxonomy_prompt_block",
    "validate_backend_config",
    "write_jsonl",
]
